/* Acton source hash: test-hash */
#pragma once
#include "builtin/builtin.h"
#include "rts/rts.h"
struct deactQ_L_2Cont;
struct deactQ_L_4action;
struct deactQ_L_6Cont;
struct deactQ_L_7proc;
struct deactQ_L_8proc;
struct deactQ_L_9proc;
struct deactQ_L_10proc;
struct deactQ_L_14action;
struct deactQ_L_16action;
struct deactQ_L_19action;
struct deactQ_L_20Cont;
struct deactQ_L_21Cont;
struct deactQ_L_22Cont;
struct deactQ_L_23proc;
struct deactQ_L_25Cont;
struct deactQ_L_26proc;
struct deactQ_L_28Cont;
struct deactQ_L_29proc;
struct deactQ_L_31Cont;
struct deactQ_L_32proc;
struct deactQ_Apa;
struct deactQ_Bepa;
struct deactQ_main;
typedef struct deactQ_L_2Cont *deactQ_L_2Cont;
typedef struct deactQ_L_4action *deactQ_L_4action;
typedef struct deactQ_L_6Cont *deactQ_L_6Cont;
typedef struct deactQ_L_7proc *deactQ_L_7proc;
typedef struct deactQ_L_8proc *deactQ_L_8proc;
typedef struct deactQ_L_9proc *deactQ_L_9proc;
typedef struct deactQ_L_10proc *deactQ_L_10proc;
typedef struct deactQ_L_14action *deactQ_L_14action;
typedef struct deactQ_L_16action *deactQ_L_16action;
typedef struct deactQ_L_19action *deactQ_L_19action;
typedef struct deactQ_L_20Cont *deactQ_L_20Cont;
typedef struct deactQ_L_21Cont *deactQ_L_21Cont;
typedef struct deactQ_L_22Cont *deactQ_L_22Cont;
typedef struct deactQ_L_23proc *deactQ_L_23proc;
typedef struct deactQ_L_25Cont *deactQ_L_25Cont;
typedef struct deactQ_L_26proc *deactQ_L_26proc;
typedef struct deactQ_L_28Cont *deactQ_L_28Cont;
typedef struct deactQ_L_29proc *deactQ_L_29proc;
typedef struct deactQ_L_31Cont *deactQ_L_31Cont;
typedef struct deactQ_L_32proc *deactQ_L_32proc;
typedef struct deactQ_Apa *deactQ_Apa;
typedef struct deactQ_Bepa *deactQ_Bepa;
typedef struct deactQ_main *deactQ_main;
$R deactQ_L_1C_1cont ($Cont, B_NoneType);
struct deactQ_L_2ContG_class {
    char *$GCINFO;
    int $class_id;
    $SuperG_class $superclass;
    B_NoneType (*__init__) (deactQ_L_2Cont, $Cont);
    void (*__serialize__) (deactQ_L_2Cont, $Serial$state);
    deactQ_L_2Cont (*__deserialize__) (deactQ_L_2Cont, $Serial$state);
    B_bool (*__bool__) (deactQ_L_2Cont);
    B_str (*__str__) (deactQ_L_2Cont);
    B_str (*__repr__) (deactQ_L_2Cont);
    $R (*__call__) (deactQ_L_2Cont, B_NoneType);
};
struct deactQ_L_2Cont {
    struct deactQ_L_2ContG_class *$class;
    $Cont C_cont;
};
struct deactQ_L_4actionG_class {
    char *$GCINFO;
    int $class_id;
    $SuperG_class $superclass;
    B_NoneType (*__init__) (deactQ_L_4action, deactQ_Apa);
    void (*__serialize__) (deactQ_L_4action, $Serial$state);
    deactQ_L_4action (*__deserialize__) (deactQ_L_4action, $Serial$state);
    B_bool (*__bool__) (deactQ_L_4action);
    B_str (*__str__) (deactQ_L_4action);
    B_str (*__repr__) (deactQ_L_4action);
    $R (*__call__) (deactQ_L_4action, $Cont, B_int);
    $R (*__exec__) (deactQ_L_4action, $Cont, B_int);
    B_Msg (*__asyn__) (deactQ_L_4action, B_int);
};
struct deactQ_L_4action {
    struct deactQ_L_4actionG_class *$class;
    deactQ_Apa L_3obj;
};
$R deactQ_U_L_5C_3cont ($action, $Cont, int64_t);
$R deactQ_L_5C_3cont ($action, $Cont, B_int);
struct deactQ_L_6ContG_class {
    char *$GCINFO;
    int $class_id;
    $SuperG_class $superclass;
    B_NoneType (*__init__) (deactQ_L_6Cont, $action, $Cont);
    void (*__serialize__) (deactQ_L_6Cont, $Serial$state);
    deactQ_L_6Cont (*__deserialize__) (deactQ_L_6Cont, $Serial$state);
    B_bool (*__bool__) (deactQ_L_6Cont);
    B_str (*__str__) (deactQ_L_6Cont);
    B_str (*__repr__) (deactQ_L_6Cont);
    $R (*__call__) (deactQ_L_6Cont, B_int);
};
struct deactQ_L_6Cont {
    struct deactQ_L_6ContG_class *$class;
    $action cb;
    $Cont C_cont;
};
struct deactQ_L_7procG_class {
    char *$GCINFO;
    int $class_id;
    $SuperG_class $superclass;
    B_NoneType (*__init__) (deactQ_L_7proc, deactQ_Apa, $action);
    void (*__serialize__) (deactQ_L_7proc, $Serial$state);
    deactQ_L_7proc (*__deserialize__) (deactQ_L_7proc, $Serial$state);
    B_bool (*__bool__) (deactQ_L_7proc);
    B_str (*__str__) (deactQ_L_7proc);
    B_str (*__repr__) (deactQ_L_7proc);
    $R (*__call__) (deactQ_L_7proc, $Cont);
    $R (*__exec__) (deactQ_L_7proc, $Cont);
};
struct deactQ_L_7proc {
    struct deactQ_L_7procG_class *$class;
    deactQ_Apa self;
    $action cb;
};
struct deactQ_L_8procG_class {
    char *$GCINFO;
    int $class_id;
    $SuperG_class $superclass;
    B_NoneType (*__init__) (deactQ_L_8proc, deactQ_Apa, $action);
    void (*__serialize__) (deactQ_L_8proc, $Serial$state);
    deactQ_L_8proc (*__deserialize__) (deactQ_L_8proc, $Serial$state);
    B_bool (*__bool__) (deactQ_L_8proc);
    B_str (*__str__) (deactQ_L_8proc);
    B_str (*__repr__) (deactQ_L_8proc);
    $R (*__call__) (deactQ_L_8proc, $Cont);
    $R (*__exec__) (deactQ_L_8proc, $Cont);
};
struct deactQ_L_8proc {
    struct deactQ_L_8procG_class *$class;
    deactQ_Apa self;
    $action cb;
};
struct deactQ_L_9procG_class {
    char *$GCINFO;
    int $class_id;
    $SuperG_class $superclass;
    B_NoneType (*__init__) (deactQ_L_9proc, deactQ_Apa, B_int);
    void (*__serialize__) (deactQ_L_9proc, $Serial$state);
    deactQ_L_9proc (*__deserialize__) (deactQ_L_9proc, $Serial$state);
    B_bool (*__bool__) (deactQ_L_9proc);
    B_str (*__str__) (deactQ_L_9proc);
    B_str (*__repr__) (deactQ_L_9proc);
    $R (*__call__) (deactQ_L_9proc, $Cont);
    $R (*__exec__) (deactQ_L_9proc, $Cont);
};
struct deactQ_L_9proc {
    struct deactQ_L_9procG_class *$class;
    deactQ_Apa self;
    B_int i;
};
struct deactQ_L_10procG_class {
    char *$GCINFO;
    int $class_id;
    $SuperG_class $superclass;
    B_NoneType (*__init__) (deactQ_L_10proc, deactQ_Bepa, B_int);
    void (*__serialize__) (deactQ_L_10proc, $Serial$state);
    deactQ_L_10proc (*__deserialize__) (deactQ_L_10proc, $Serial$state);
    B_bool (*__bool__) (deactQ_L_10proc);
    B_str (*__str__) (deactQ_L_10proc);
    B_str (*__repr__) (deactQ_L_10proc);
    $R (*__call__) (deactQ_L_10proc, $Cont);
    $R (*__exec__) (deactQ_L_10proc, $Cont);
};
struct deactQ_L_10proc {
    struct deactQ_L_10procG_class *$class;
    deactQ_Bepa self;
    B_int i;
};
struct deactQ_L_14actionG_class {
    char *$GCINFO;
    int $class_id;
    $SuperG_class $superclass;
    B_NoneType (*__init__) (deactQ_L_14action, deactQ_Apa);
    void (*__serialize__) (deactQ_L_14action, $Serial$state);
    deactQ_L_14action (*__deserialize__) (deactQ_L_14action, $Serial$state);
    B_bool (*__bool__) (deactQ_L_14action);
    B_str (*__str__) (deactQ_L_14action);
    B_str (*__repr__) (deactQ_L_14action);
    $R (*__call__) (deactQ_L_14action, $Cont, B_int);
    $R (*__exec__) (deactQ_L_14action, $Cont, B_int);
    B_Msg (*__asyn__) (deactQ_L_14action, B_int);
};
struct deactQ_L_14action {
    struct deactQ_L_14actionG_class *$class;
    deactQ_Apa L_13obj;
};
struct deactQ_L_16actionG_class {
    char *$GCINFO;
    int $class_id;
    $SuperG_class $superclass;
    B_NoneType (*__init__) (deactQ_L_16action, deactQ_Bepa);
    void (*__serialize__) (deactQ_L_16action, $Serial$state);
    deactQ_L_16action (*__deserialize__) (deactQ_L_16action, $Serial$state);
    B_bool (*__bool__) (deactQ_L_16action);
    B_str (*__str__) (deactQ_L_16action);
    B_str (*__repr__) (deactQ_L_16action);
    $R (*__call__) (deactQ_L_16action, $Cont, B_int);
    $R (*__exec__) (deactQ_L_16action, $Cont, B_int);
    B_Msg (*__asyn__) (deactQ_L_16action, B_int);
};
struct deactQ_L_16action {
    struct deactQ_L_16actionG_class *$class;
    deactQ_Bepa L_15obj;
};
struct deactQ_L_19actionG_class {
    char *$GCINFO;
    int $class_id;
    $SuperG_class $superclass;
    B_NoneType (*__init__) (deactQ_L_19action, deactQ_main);
    void (*__serialize__) (deactQ_L_19action, $Serial$state);
    deactQ_L_19action (*__deserialize__) (deactQ_L_19action, $Serial$state);
    B_bool (*__bool__) (deactQ_L_19action);
    B_str (*__str__) (deactQ_L_19action);
    B_str (*__repr__) (deactQ_L_19action);
    $R (*__call__) (deactQ_L_19action, $Cont, B_int);
    $R (*__exec__) (deactQ_L_19action, $Cont, B_int);
    B_Msg (*__asyn__) (deactQ_L_19action, B_int);
};
struct deactQ_L_19action {
    struct deactQ_L_19actionG_class *$class;
    deactQ_main L_18obj;
};
$R deactQ_U_1L_17C_9cont (deactQ_main, $Cont, int64_t);
$R deactQ_L_17C_9cont (deactQ_main, $Cont, B_int);
struct deactQ_L_20ContG_class {
    char *$GCINFO;
    int $class_id;
    $SuperG_class $superclass;
    B_NoneType (*__init__) (deactQ_L_20Cont, deactQ_main, $Cont);
    void (*__serialize__) (deactQ_L_20Cont, $Serial$state);
    deactQ_L_20Cont (*__deserialize__) (deactQ_L_20Cont, $Serial$state);
    B_bool (*__bool__) (deactQ_L_20Cont);
    B_str (*__str__) (deactQ_L_20Cont);
    B_str (*__repr__) (deactQ_L_20Cont);
    $R (*__call__) (deactQ_L_20Cont, B_int);
};
struct deactQ_L_20Cont {
    struct deactQ_L_20ContG_class *$class;
    deactQ_main self;
    $Cont C_cont;
};
$R deactQ_L_12C_7cont (deactQ_main, $Cont, deactQ_Bepa);
struct deactQ_L_21ContG_class {
    char *$GCINFO;
    int $class_id;
    $SuperG_class $superclass;
    B_NoneType (*__init__) (deactQ_L_21Cont, deactQ_main, $Cont);
    void (*__serialize__) (deactQ_L_21Cont, $Serial$state);
    deactQ_L_21Cont (*__deserialize__) (deactQ_L_21Cont, $Serial$state);
    B_bool (*__bool__) (deactQ_L_21Cont);
    B_str (*__str__) (deactQ_L_21Cont);
    B_str (*__repr__) (deactQ_L_21Cont);
    $R (*__call__) (deactQ_L_21Cont, deactQ_Bepa);
};
struct deactQ_L_21Cont {
    struct deactQ_L_21ContG_class *$class;
    deactQ_main self;
    $Cont C_cont;
};
$R deactQ_L_11C_5cont (deactQ_main, $Cont, deactQ_Apa);
struct deactQ_L_22ContG_class {
    char *$GCINFO;
    int $class_id;
    $SuperG_class $superclass;
    B_NoneType (*__init__) (deactQ_L_22Cont, deactQ_main, $Cont);
    void (*__serialize__) (deactQ_L_22Cont, $Serial$state);
    deactQ_L_22Cont (*__deserialize__) (deactQ_L_22Cont, $Serial$state);
    B_bool (*__bool__) (deactQ_L_22Cont);
    B_str (*__str__) (deactQ_L_22Cont);
    B_str (*__repr__) (deactQ_L_22Cont);
    $R (*__call__) (deactQ_L_22Cont, deactQ_Apa);
};
struct deactQ_L_22Cont {
    struct deactQ_L_22ContG_class *$class;
    deactQ_main self;
    $Cont C_cont;
};
struct deactQ_L_23procG_class {
    char *$GCINFO;
    int $class_id;
    $SuperG_class $superclass;
    B_NoneType (*__init__) (deactQ_L_23proc, deactQ_main, B_int);
    void (*__serialize__) (deactQ_L_23proc, $Serial$state);
    deactQ_L_23proc (*__deserialize__) (deactQ_L_23proc, $Serial$state);
    B_bool (*__bool__) (deactQ_L_23proc);
    B_str (*__str__) (deactQ_L_23proc);
    B_str (*__repr__) (deactQ_L_23proc);
    $R (*__call__) (deactQ_L_23proc, $Cont);
    $R (*__exec__) (deactQ_L_23proc, $Cont);
};
struct deactQ_L_23proc {
    struct deactQ_L_23procG_class *$class;
    deactQ_main self;
    B_int i;
};
$R deactQ_L_24C_11cont ($Cont, deactQ_Apa, B_NoneType);
struct deactQ_L_25ContG_class {
    char *$GCINFO;
    int $class_id;
    $SuperG_class $superclass;
    B_NoneType (*__init__) (deactQ_L_25Cont, $Cont, deactQ_Apa);
    void (*__serialize__) (deactQ_L_25Cont, $Serial$state);
    deactQ_L_25Cont (*__deserialize__) (deactQ_L_25Cont, $Serial$state);
    B_bool (*__bool__) (deactQ_L_25Cont);
    B_str (*__str__) (deactQ_L_25Cont);
    B_str (*__repr__) (deactQ_L_25Cont);
    $R (*__call__) (deactQ_L_25Cont, B_NoneType);
};
struct deactQ_L_25Cont {
    struct deactQ_L_25ContG_class *$class;
    $Cont C_cont;
    deactQ_Apa G_act;
};
struct deactQ_L_26procG_class {
    char *$GCINFO;
    int $class_id;
    $SuperG_class $superclass;
    B_NoneType (*__init__) (deactQ_L_26proc, deactQ_Apa);
    void (*__serialize__) (deactQ_L_26proc, $Serial$state);
    deactQ_L_26proc (*__deserialize__) (deactQ_L_26proc, $Serial$state);
    B_bool (*__bool__) (deactQ_L_26proc);
    B_str (*__str__) (deactQ_L_26proc);
    B_str (*__repr__) (deactQ_L_26proc);
    $R (*__call__) (deactQ_L_26proc, $Cont);
    $R (*__exec__) (deactQ_L_26proc, $Cont);
};
struct deactQ_L_26proc {
    struct deactQ_L_26procG_class *$class;
    deactQ_Apa G_act;
};
$R deactQ_L_27C_13cont ($Cont, deactQ_Bepa, B_NoneType);
struct deactQ_L_28ContG_class {
    char *$GCINFO;
    int $class_id;
    $SuperG_class $superclass;
    B_NoneType (*__init__) (deactQ_L_28Cont, $Cont, deactQ_Bepa);
    void (*__serialize__) (deactQ_L_28Cont, $Serial$state);
    deactQ_L_28Cont (*__deserialize__) (deactQ_L_28Cont, $Serial$state);
    B_bool (*__bool__) (deactQ_L_28Cont);
    B_str (*__str__) (deactQ_L_28Cont);
    B_str (*__repr__) (deactQ_L_28Cont);
    $R (*__call__) (deactQ_L_28Cont, B_NoneType);
};
struct deactQ_L_28Cont {
    struct deactQ_L_28ContG_class *$class;
    $Cont C_cont;
    deactQ_Bepa G_act;
};
struct deactQ_L_29procG_class {
    char *$GCINFO;
    int $class_id;
    $SuperG_class $superclass;
    B_NoneType (*__init__) (deactQ_L_29proc, deactQ_Bepa);
    void (*__serialize__) (deactQ_L_29proc, $Serial$state);
    deactQ_L_29proc (*__deserialize__) (deactQ_L_29proc, $Serial$state);
    B_bool (*__bool__) (deactQ_L_29proc);
    B_str (*__str__) (deactQ_L_29proc);
    B_str (*__repr__) (deactQ_L_29proc);
    $R (*__call__) (deactQ_L_29proc, $Cont);
    $R (*__exec__) (deactQ_L_29proc, $Cont);
};
struct deactQ_L_29proc {
    struct deactQ_L_29procG_class *$class;
    deactQ_Bepa G_act;
};
$R deactQ_L_30C_15cont ($Cont, deactQ_main, B_NoneType);
struct deactQ_L_31ContG_class {
    char *$GCINFO;
    int $class_id;
    $SuperG_class $superclass;
    B_NoneType (*__init__) (deactQ_L_31Cont, $Cont, deactQ_main);
    void (*__serialize__) (deactQ_L_31Cont, $Serial$state);
    deactQ_L_31Cont (*__deserialize__) (deactQ_L_31Cont, $Serial$state);
    B_bool (*__bool__) (deactQ_L_31Cont);
    B_str (*__str__) (deactQ_L_31Cont);
    B_str (*__repr__) (deactQ_L_31Cont);
    $R (*__call__) (deactQ_L_31Cont, B_NoneType);
};
struct deactQ_L_31Cont {
    struct deactQ_L_31ContG_class *$class;
    $Cont C_cont;
    deactQ_main G_act;
};
struct deactQ_L_32procG_class {
    char *$GCINFO;
    int $class_id;
    $SuperG_class $superclass;
    B_NoneType (*__init__) (deactQ_L_32proc, deactQ_main, B_Env);
    void (*__serialize__) (deactQ_L_32proc, $Serial$state);
    deactQ_L_32proc (*__deserialize__) (deactQ_L_32proc, $Serial$state);
    B_bool (*__bool__) (deactQ_L_32proc);
    B_str (*__str__) (deactQ_L_32proc);
    B_str (*__repr__) (deactQ_L_32proc);
    $R (*__call__) (deactQ_L_32proc, $Cont);
    $R (*__exec__) (deactQ_L_32proc, $Cont);
};
struct deactQ_L_32proc {
    struct deactQ_L_32procG_class *$class;
    deactQ_main G_act;
    B_Env env;
};
struct deactQ_ApaG_class {
    char *$GCINFO;
    int $class_id;
    $SuperG_class $superclass;
    $R (*__init__) (deactQ_Apa, $Cont);
    void (*__serialize__) (deactQ_Apa, $Serial$state);
    deactQ_Apa (*__deserialize__) (deactQ_Apa, $Serial$state);
    B_bool (*__bool__) (deactQ_Apa);
    B_str (*__str__) (deactQ_Apa);
    B_str (*__repr__) (deactQ_Apa);
    B_NoneType (*__resume__) (deactQ_Apa);
    B_NoneType (*__cleanup__) (deactQ_Apa);
    $R (*setupG_local) (deactQ_Apa, $Cont, $action);
    $R (*computeG_local) (deactQ_Apa, $Cont, $action);
    $R (*noticeG_local) (deactQ_Apa, $Cont, B_int);
    B_Msg (*setup) (deactQ_Apa, $action);
    B_Msg (*compute) (deactQ_Apa, $action);
    B_Msg (*notice) (deactQ_Apa, B_int);
};
struct deactQ_Apa {
    struct deactQ_ApaG_class *$class;
    $Actor $next;
    B_Msg $msg;
    B_Msg $msg_tail;
    $Lock $msg_lock;
    $int64 $affinity;
    B_Msg $outgoing;
    B_Msg $waitsfor;
    $int64 $consume_hd;
    $Catcher $catcher;
    $long $globkey;
};
struct deactQ_BepaG_class {
    char *$GCINFO;
    int $class_id;
    $SuperG_class $superclass;
    $R (*__init__) (deactQ_Bepa, $Cont);
    void (*__serialize__) (deactQ_Bepa, $Serial$state);
    deactQ_Bepa (*__deserialize__) (deactQ_Bepa, $Serial$state);
    B_bool (*__bool__) (deactQ_Bepa);
    B_str (*__str__) (deactQ_Bepa);
    B_str (*__repr__) (deactQ_Bepa);
    B_NoneType (*__resume__) (deactQ_Bepa);
    B_NoneType (*__cleanup__) (deactQ_Bepa);
    $R (*callbackG_local) (deactQ_Bepa, $Cont, B_int);
    B_Msg (*callback) (deactQ_Bepa, B_int);
};
struct deactQ_Bepa {
    struct deactQ_BepaG_class *$class;
    $Actor $next;
    B_Msg $msg;
    B_Msg $msg_tail;
    $Lock $msg_lock;
    $int64 $affinity;
    B_Msg $outgoing;
    B_Msg $waitsfor;
    $int64 $consume_hd;
    $Catcher $catcher;
    $long $globkey;
};
struct deactQ_mainG_class {
    char *$GCINFO;
    int $class_id;
    $SuperG_class $superclass;
    $R (*__init__) (deactQ_main, $Cont, B_Env);
    void (*__serialize__) (deactQ_main, $Serial$state);
    deactQ_main (*__deserialize__) (deactQ_main, $Serial$state);
    B_bool (*__bool__) (deactQ_main);
    B_str (*__str__) (deactQ_main);
    B_str (*__repr__) (deactQ_main);
    B_NoneType (*__resume__) (deactQ_main);
    B_NoneType (*__cleanup__) (deactQ_main);
    $R (*myprocG_local) (deactQ_main, $Cont, B_int);
    B_Msg (*myproc) (deactQ_main, B_int);
};
struct deactQ_main {
    struct deactQ_mainG_class *$class;
    $Actor $next;
    B_Msg $msg;
    B_Msg $msg_tail;
    $Lock $msg_lock;
    $int64 $affinity;
    B_Msg $outgoing;
    B_Msg $waitsfor;
    $int64 $consume_hd;
    $Catcher $catcher;
    $long $globkey;
    B_Env env;
    deactQ_Apa a;
    deactQ_Bepa b;
    B_Msg x;
    B_int r;
};
$R deactQ_ApaG_newact ($Cont);
$R deactQ_BepaG_newact ($Cont);
$R deactQ_mainG_newact ($Cont, B_Env);
extern struct deactQ_L_2ContG_class deactQ_L_2ContG_methods;
deactQ_L_2Cont deactQ_L_2ContG_new($Cont);
extern struct deactQ_L_4actionG_class deactQ_L_4actionG_methods;
deactQ_L_4action deactQ_L_4actionG_new(deactQ_Apa);
extern struct deactQ_L_6ContG_class deactQ_L_6ContG_methods;
deactQ_L_6Cont deactQ_L_6ContG_new($action, $Cont);
extern struct deactQ_L_7procG_class deactQ_L_7procG_methods;
deactQ_L_7proc deactQ_L_7procG_new(deactQ_Apa, $action);
extern struct deactQ_L_8procG_class deactQ_L_8procG_methods;
deactQ_L_8proc deactQ_L_8procG_new(deactQ_Apa, $action);
extern struct deactQ_L_9procG_class deactQ_L_9procG_methods;
deactQ_L_9proc deactQ_L_9procG_new(deactQ_Apa, B_int);
extern struct deactQ_L_10procG_class deactQ_L_10procG_methods;
deactQ_L_10proc deactQ_L_10procG_new(deactQ_Bepa, B_int);
extern struct deactQ_L_14actionG_class deactQ_L_14actionG_methods;
deactQ_L_14action deactQ_L_14actionG_new(deactQ_Apa);
extern struct deactQ_L_16actionG_class deactQ_L_16actionG_methods;
deactQ_L_16action deactQ_L_16actionG_new(deactQ_Bepa);
extern struct deactQ_L_19actionG_class deactQ_L_19actionG_methods;
deactQ_L_19action deactQ_L_19actionG_new(deactQ_main);
extern struct deactQ_L_20ContG_class deactQ_L_20ContG_methods;
deactQ_L_20Cont deactQ_L_20ContG_new(deactQ_main, $Cont);
extern struct deactQ_L_21ContG_class deactQ_L_21ContG_methods;
deactQ_L_21Cont deactQ_L_21ContG_new(deactQ_main, $Cont);
extern struct deactQ_L_22ContG_class deactQ_L_22ContG_methods;
deactQ_L_22Cont deactQ_L_22ContG_new(deactQ_main, $Cont);
extern struct deactQ_L_23procG_class deactQ_L_23procG_methods;
deactQ_L_23proc deactQ_L_23procG_new(deactQ_main, B_int);
extern struct deactQ_L_25ContG_class deactQ_L_25ContG_methods;
deactQ_L_25Cont deactQ_L_25ContG_new($Cont, deactQ_Apa);
extern struct deactQ_L_26procG_class deactQ_L_26procG_methods;
deactQ_L_26proc deactQ_L_26procG_new(deactQ_Apa);
extern struct deactQ_L_28ContG_class deactQ_L_28ContG_methods;
deactQ_L_28Cont deactQ_L_28ContG_new($Cont, deactQ_Bepa);
extern struct deactQ_L_29procG_class deactQ_L_29procG_methods;
deactQ_L_29proc deactQ_L_29procG_new(deactQ_Bepa);
extern struct deactQ_L_31ContG_class deactQ_L_31ContG_methods;
deactQ_L_31Cont deactQ_L_31ContG_new($Cont, deactQ_main);
extern struct deactQ_L_32procG_class deactQ_L_32procG_methods;
deactQ_L_32proc deactQ_L_32procG_new(deactQ_main, B_Env);
extern struct deactQ_ApaG_class deactQ_ApaG_methods;
$R deactQ_ApaG_new($Cont);
extern struct deactQ_BepaG_class deactQ_BepaG_methods;
$R deactQ_BepaG_new($Cont);
extern struct deactQ_mainG_class deactQ_mainG_methods;
$R deactQ_mainG_new($Cont, B_Env);
<<<<<<< HEAD
=======
extern B_Plus deactQ_W_313;
extern B_Times deactQ_W_223;
extern B_Eq deactQ_W_761;
>>>>>>> 31837f3b (Update golden files)
void deactQ___init__ ();