/* Acton source hash: test-hash */
#pragma once
#include "builtin/builtin.h"
#include "rts/rts.h"
struct deactQ_L_2Cont;
struct deactQ_L_4proc;
struct deactQ_L_6Cont;
struct deactQ_L_8Cont;
struct deactQ_L_9proc;
struct deactQ_L_10proc;
struct deactQ_L_11proc;
struct deactQ_L_12proc;
struct deactQ_L_16action;
struct deactQ_L_18action;
struct deactQ_L_21action;
struct deactQ_L_22Cont;
struct deactQ_L_23Cont;
struct deactQ_L_24Cont;
struct deactQ_L_25proc;
struct deactQ_L_27Cont;
struct deactQ_L_28proc;
struct deactQ_L_30Cont;
struct deactQ_L_31proc;
struct deactQ_L_33Cont;
struct deactQ_L_34proc;
struct deactQ_Apa;
struct deactQ_Bepa;
struct deactQ_main;
typedef struct deactQ_L_2Cont *deactQ_L_2Cont;
typedef struct deactQ_L_4proc *deactQ_L_4proc;
typedef struct deactQ_L_6Cont *deactQ_L_6Cont;
typedef struct deactQ_L_8Cont *deactQ_L_8Cont;
typedef struct deactQ_L_9proc *deactQ_L_9proc;
typedef struct deactQ_L_10proc *deactQ_L_10proc;
typedef struct deactQ_L_11proc *deactQ_L_11proc;
typedef struct deactQ_L_12proc *deactQ_L_12proc;
typedef struct deactQ_L_16action *deactQ_L_16action;
typedef struct deactQ_L_18action *deactQ_L_18action;
typedef struct deactQ_L_21action *deactQ_L_21action;
typedef struct deactQ_L_22Cont *deactQ_L_22Cont;
typedef struct deactQ_L_23Cont *deactQ_L_23Cont;
typedef struct deactQ_L_24Cont *deactQ_L_24Cont;
typedef struct deactQ_L_25proc *deactQ_L_25proc;
typedef struct deactQ_L_27Cont *deactQ_L_27Cont;
typedef struct deactQ_L_28proc *deactQ_L_28proc;
typedef struct deactQ_L_30Cont *deactQ_L_30Cont;
typedef struct deactQ_L_31proc *deactQ_L_31proc;
typedef struct deactQ_L_33Cont *deactQ_L_33Cont;
typedef struct deactQ_L_34proc *deactQ_L_34proc;
typedef struct deactQ_Apa *deactQ_Apa;
typedef struct deactQ_Bepa *deactQ_Bepa;
typedef struct deactQ_main *deactQ_main;
$R deactQ_L_1C_1cont ($Cont, B_NoneType);
struct deactQ_L_2ContG_class {
    char *$GCINFO;
    int $class_id;
    $SuperG_class $superclass;
    B_NoneType (*__init__) (deactQ_L_2Cont, $Cont);
    void (*__serialize__) (deactQ_L_2Cont, $Serial$state);
    deactQ_L_2Cont (*__deserialize__) (deactQ_L_2Cont, $Serial$state);
    B_bool (*__bool__) (deactQ_L_2Cont);
    B_str (*__str__) (deactQ_L_2Cont);
    B_str (*__repr__) (deactQ_L_2Cont);
    $R (*__call__) (deactQ_L_2Cont, B_NoneType);
};
struct deactQ_L_2Cont {
    struct deactQ_L_2ContG_class *$class;
    $Cont C_cont;
};
struct deactQ_L_4procG_class {
    char *$GCINFO;
    int $class_id;
    $SuperG_class $superclass;
    B_NoneType (*__init__) (deactQ_L_4proc, deactQ_Apa);
    void (*__serialize__) (deactQ_L_4proc, $Serial$state);
    deactQ_L_4proc (*__deserialize__) (deactQ_L_4proc, $Serial$state);
    B_bool (*__bool__) (deactQ_L_4proc);
    B_str (*__str__) (deactQ_L_4proc);
    B_str (*__repr__) (deactQ_L_4proc);
    $R (*__call__) (deactQ_L_4proc, $Cont, B_int);
    $R (*__exec__) (deactQ_L_4proc, $Cont, B_int);
};
struct deactQ_L_4proc {
    struct deactQ_L_4procG_class *$class;
    deactQ_Apa L_3obj;
};
$R deactQ_U_L_5C_3cont ($Cont, int64_t);
$R deactQ_L_5C_3cont ($Cont, B_int);
struct deactQ_L_6ContG_class {
    char *$GCINFO;
    int $class_id;
    $SuperG_class $superclass;
    B_NoneType (*__init__) (deactQ_L_6Cont, $Cont);
    void (*__serialize__) (deactQ_L_6Cont, $Serial$state);
    deactQ_L_6Cont (*__deserialize__) (deactQ_L_6Cont, $Serial$state);
    B_bool (*__bool__) (deactQ_L_6Cont);
    B_str (*__str__) (deactQ_L_6Cont);
    B_str (*__repr__) (deactQ_L_6Cont);
    $R (*__call__) (deactQ_L_6Cont, B_int);
};
struct deactQ_L_6Cont {
    struct deactQ_L_6ContG_class *$class;
    $Cont C_cont;
};
$R deactQ_U_1L_7C_5cont ($action, $Cont, int64_t);
$R deactQ_L_7C_5cont ($action, $Cont, B_int);
struct deactQ_L_8ContG_class {
    char *$GCINFO;
    int $class_id;
    $SuperG_class $superclass;
    B_NoneType (*__init__) (deactQ_L_8Cont, $action, $Cont);
    void (*__serialize__) (deactQ_L_8Cont, $Serial$state);
    deactQ_L_8Cont (*__deserialize__) (deactQ_L_8Cont, $Serial$state);
    B_bool (*__bool__) (deactQ_L_8Cont);
    B_str (*__str__) (deactQ_L_8Cont);
    B_str (*__repr__) (deactQ_L_8Cont);
    $R (*__call__) (deactQ_L_8Cont, B_int);
};
struct deactQ_L_8Cont {
    struct deactQ_L_8ContG_class *$class;
    $action cb;
    $Cont C_cont;
};
struct deactQ_L_9procG_class {
    char *$GCINFO;
    int $class_id;
    $SuperG_class $superclass;
    B_NoneType (*__init__) (deactQ_L_9proc, deactQ_Apa, $proc);
    void (*__serialize__) (deactQ_L_9proc, $Serial$state);
    deactQ_L_9proc (*__deserialize__) (deactQ_L_9proc, $Serial$state);
    B_bool (*__bool__) (deactQ_L_9proc);
    B_str (*__str__) (deactQ_L_9proc);
    B_str (*__repr__) (deactQ_L_9proc);
    $R (*__call__) (deactQ_L_9proc, $Cont);
    $R (*__exec__) (deactQ_L_9proc, $Cont);
};
struct deactQ_L_9proc {
    struct deactQ_L_9procG_class *$class;
    deactQ_Apa self;
    $proc cb;
};
struct deactQ_L_10procG_class {
    char *$GCINFO;
    int $class_id;
    $SuperG_class $superclass;
    B_NoneType (*__init__) (deactQ_L_10proc, deactQ_Apa, $action);
    void (*__serialize__) (deactQ_L_10proc, $Serial$state);
    deactQ_L_10proc (*__deserialize__) (deactQ_L_10proc, $Serial$state);
    B_bool (*__bool__) (deactQ_L_10proc);
    B_str (*__str__) (deactQ_L_10proc);
    B_str (*__repr__) (deactQ_L_10proc);
    $R (*__call__) (deactQ_L_10proc, $Cont);
    $R (*__exec__) (deactQ_L_10proc, $Cont);
};
struct deactQ_L_10proc {
    struct deactQ_L_10procG_class *$class;
    deactQ_Apa self;
    $action cb;
};
struct deactQ_L_11procG_class {
    char *$GCINFO;
    int $class_id;
    $SuperG_class $superclass;
    B_NoneType (*__init__) (deactQ_L_11proc, deactQ_Apa, B_int);
    void (*__serialize__) (deactQ_L_11proc, $Serial$state);
    deactQ_L_11proc (*__deserialize__) (deactQ_L_11proc, $Serial$state);
    B_bool (*__bool__) (deactQ_L_11proc);
    B_str (*__str__) (deactQ_L_11proc);
    B_str (*__repr__) (deactQ_L_11proc);
    $R (*__call__) (deactQ_L_11proc, $Cont);
    $R (*__exec__) (deactQ_L_11proc, $Cont);
};
struct deactQ_L_11proc {
    struct deactQ_L_11procG_class *$class;
    deactQ_Apa self;
    B_int i;
};
struct deactQ_L_12procG_class {
    char *$GCINFO;
    int $class_id;
    $SuperG_class $superclass;
    B_NoneType (*__init__) (deactQ_L_12proc, deactQ_Bepa, B_int);
    void (*__serialize__) (deactQ_L_12proc, $Serial$state);
    deactQ_L_12proc (*__deserialize__) (deactQ_L_12proc, $Serial$state);
    B_bool (*__bool__) (deactQ_L_12proc);
    B_str (*__str__) (deactQ_L_12proc);
    B_str (*__repr__) (deactQ_L_12proc);
    $R (*__call__) (deactQ_L_12proc, $Cont);
    $R (*__exec__) (deactQ_L_12proc, $Cont);
};
struct deactQ_L_12proc {
    struct deactQ_L_12procG_class *$class;
    deactQ_Bepa self;
    B_int i;
};
struct deactQ_L_16actionG_class {
    char *$GCINFO;
    int $class_id;
    $SuperG_class $superclass;
    B_NoneType (*__init__) (deactQ_L_16action, deactQ_Apa);
    void (*__serialize__) (deactQ_L_16action, $Serial$state);
    deactQ_L_16action (*__deserialize__) (deactQ_L_16action, $Serial$state);
    B_bool (*__bool__) (deactQ_L_16action);
    B_str (*__str__) (deactQ_L_16action);
    B_str (*__repr__) (deactQ_L_16action);
    $R (*__call__) (deactQ_L_16action, $Cont, B_int);
    $R (*__exec__) (deactQ_L_16action, $Cont, B_int);
    B_Msg (*__asyn__) (deactQ_L_16action, B_int);
};
struct deactQ_L_16action {
    struct deactQ_L_16actionG_class *$class;
    deactQ_Apa L_15obj;
};
struct deactQ_L_18actionG_class {
    char *$GCINFO;
    int $class_id;
    $SuperG_class $superclass;
    B_NoneType (*__init__) (deactQ_L_18action, deactQ_Bepa);
    void (*__serialize__) (deactQ_L_18action, $Serial$state);
    deactQ_L_18action (*__deserialize__) (deactQ_L_18action, $Serial$state);
    B_bool (*__bool__) (deactQ_L_18action);
    B_str (*__str__) (deactQ_L_18action);
    B_str (*__repr__) (deactQ_L_18action);
    $R (*__call__) (deactQ_L_18action, $Cont, B_int);
    $R (*__exec__) (deactQ_L_18action, $Cont, B_int);
    B_Msg (*__asyn__) (deactQ_L_18action, B_int);
};
struct deactQ_L_18action {
    struct deactQ_L_18actionG_class *$class;
    deactQ_Bepa L_17obj;
};
struct deactQ_L_21actionG_class {
    char *$GCINFO;
    int $class_id;
    $SuperG_class $superclass;
    B_NoneType (*__init__) (deactQ_L_21action, deactQ_main);
    void (*__serialize__) (deactQ_L_21action, $Serial$state);
    deactQ_L_21action (*__deserialize__) (deactQ_L_21action, $Serial$state);
    B_bool (*__bool__) (deactQ_L_21action);
    B_str (*__str__) (deactQ_L_21action);
    B_str (*__repr__) (deactQ_L_21action);
    $R (*__call__) (deactQ_L_21action, $Cont, B_int);
    $R (*__exec__) (deactQ_L_21action, $Cont, B_int);
    B_Msg (*__asyn__) (deactQ_L_21action, B_int);
};
struct deactQ_L_21action {
    struct deactQ_L_21actionG_class *$class;
    deactQ_main L_20obj;
};
$R deactQ_U_2L_19C_11cont (deactQ_main, $Cont, int64_t);
$R deactQ_L_19C_11cont (deactQ_main, $Cont, B_int);
struct deactQ_L_22ContG_class {
    char *$GCINFO;
    int $class_id;
    $SuperG_class $superclass;
    B_NoneType (*__init__) (deactQ_L_22Cont, deactQ_main, $Cont);
    void (*__serialize__) (deactQ_L_22Cont, $Serial$state);
    deactQ_L_22Cont (*__deserialize__) (deactQ_L_22Cont, $Serial$state);
    B_bool (*__bool__) (deactQ_L_22Cont);
    B_str (*__str__) (deactQ_L_22Cont);
    B_str (*__repr__) (deactQ_L_22Cont);
    $R (*__call__) (deactQ_L_22Cont, B_int);
};
struct deactQ_L_22Cont {
    struct deactQ_L_22ContG_class *$class;
    deactQ_main self;
    $Cont C_cont;
};
$R deactQ_L_14C_9cont (deactQ_main, $Cont, deactQ_Bepa);
struct deactQ_L_23ContG_class {
    char *$GCINFO;
    int $class_id;
    $SuperG_class $superclass;
    B_NoneType (*__init__) (deactQ_L_23Cont, deactQ_main, $Cont);
    void (*__serialize__) (deactQ_L_23Cont, $Serial$state);
    deactQ_L_23Cont (*__deserialize__) (deactQ_L_23Cont, $Serial$state);
    B_bool (*__bool__) (deactQ_L_23Cont);
    B_str (*__str__) (deactQ_L_23Cont);
    B_str (*__repr__) (deactQ_L_23Cont);
    $R (*__call__) (deactQ_L_23Cont, deactQ_Bepa);
};
struct deactQ_L_23Cont {
    struct deactQ_L_23ContG_class *$class;
    deactQ_main self;
    $Cont C_cont;
};
$R deactQ_L_13C_7cont (deactQ_main, $Cont, deactQ_Apa);
struct deactQ_L_24ContG_class {
    char *$GCINFO;
    int $class_id;
    $SuperG_class $superclass;
    B_NoneType (*__init__) (deactQ_L_24Cont, deactQ_main, $Cont);
    void (*__serialize__) (deactQ_L_24Cont, $Serial$state);
    deactQ_L_24Cont (*__deserialize__) (deactQ_L_24Cont, $Serial$state);
    B_bool (*__bool__) (deactQ_L_24Cont);
    B_str (*__str__) (deactQ_L_24Cont);
    B_str (*__repr__) (deactQ_L_24Cont);
    $R (*__call__) (deactQ_L_24Cont, deactQ_Apa);
};
struct deactQ_L_24Cont {
    struct deactQ_L_24ContG_class *$class;
    deactQ_main self;
    $Cont C_cont;
};
struct deactQ_L_25procG_class {
    char *$GCINFO;
    int $class_id;
    $SuperG_class $superclass;
    B_NoneType (*__init__) (deactQ_L_25proc, deactQ_main, B_int);
    void (*__serialize__) (deactQ_L_25proc, $Serial$state);
    deactQ_L_25proc (*__deserialize__) (deactQ_L_25proc, $Serial$state);
    B_bool (*__bool__) (deactQ_L_25proc);
    B_str (*__str__) (deactQ_L_25proc);
    B_str (*__repr__) (deactQ_L_25proc);
    $R (*__call__) (deactQ_L_25proc, $Cont);
    $R (*__exec__) (deactQ_L_25proc, $Cont);
};
struct deactQ_L_25proc {
    struct deactQ_L_25procG_class *$class;
    deactQ_main self;
    B_int i;
};
$R deactQ_L_26C_13cont ($Cont, deactQ_Apa, B_NoneType);
struct deactQ_L_27ContG_class {
    char *$GCINFO;
    int $class_id;
    $SuperG_class $superclass;
    B_NoneType (*__init__) (deactQ_L_27Cont, $Cont, deactQ_Apa);
    void (*__serialize__) (deactQ_L_27Cont, $Serial$state);
    deactQ_L_27Cont (*__deserialize__) (deactQ_L_27Cont, $Serial$state);
    B_bool (*__bool__) (deactQ_L_27Cont);
    B_str (*__str__) (deactQ_L_27Cont);
    B_str (*__repr__) (deactQ_L_27Cont);
    $R (*__call__) (deactQ_L_27Cont, B_NoneType);
};
struct deactQ_L_27Cont {
    struct deactQ_L_27ContG_class *$class;
    $Cont C_cont;
    deactQ_Apa G_act;
};
struct deactQ_L_28procG_class {
    char *$GCINFO;
    int $class_id;
    $SuperG_class $superclass;
    B_NoneType (*__init__) (deactQ_L_28proc, deactQ_Apa);
    void (*__serialize__) (deactQ_L_28proc, $Serial$state);
    deactQ_L_28proc (*__deserialize__) (deactQ_L_28proc, $Serial$state);
    B_bool (*__bool__) (deactQ_L_28proc);
    B_str (*__str__) (deactQ_L_28proc);
    B_str (*__repr__) (deactQ_L_28proc);
    $R (*__call__) (deactQ_L_28proc, $Cont);
    $R (*__exec__) (deactQ_L_28proc, $Cont);
};
struct deactQ_L_28proc {
    struct deactQ_L_28procG_class *$class;
    deactQ_Apa G_act;
};
$R deactQ_L_29C_15cont ($Cont, deactQ_Bepa, B_NoneType);
struct deactQ_L_30ContG_class {
    char *$GCINFO;
    int $class_id;
    $SuperG_class $superclass;
    B_NoneType (*__init__) (deactQ_L_30Cont, $Cont, deactQ_Bepa);
    void (*__serialize__) (deactQ_L_30Cont, $Serial$state);
    deactQ_L_30Cont (*__deserialize__) (deactQ_L_30Cont, $Serial$state);
    B_bool (*__bool__) (deactQ_L_30Cont);
    B_str (*__str__) (deactQ_L_30Cont);
    B_str (*__repr__) (deactQ_L_30Cont);
    $R (*__call__) (deactQ_L_30Cont, B_NoneType);
};
struct deactQ_L_30Cont {
    struct deactQ_L_30ContG_class *$class;
    $Cont C_cont;
    deactQ_Bepa G_act;
};
struct deactQ_L_31procG_class {
    char *$GCINFO;
    int $class_id;
    $SuperG_class $superclass;
    B_NoneType (*__init__) (deactQ_L_31proc, deactQ_Bepa);
    void (*__serialize__) (deactQ_L_31proc, $Serial$state);
    deactQ_L_31proc (*__deserialize__) (deactQ_L_31proc, $Serial$state);
    B_bool (*__bool__) (deactQ_L_31proc);
    B_str (*__str__) (deactQ_L_31proc);
    B_str (*__repr__) (deactQ_L_31proc);
    $R (*__call__) (deactQ_L_31proc, $Cont);
    $R (*__exec__) (deactQ_L_31proc, $Cont);
};
struct deactQ_L_31proc {
    struct deactQ_L_31procG_class *$class;
    deactQ_Bepa G_act;
};
$R deactQ_L_32C_17cont ($Cont, deactQ_main, B_NoneType);
struct deactQ_L_33ContG_class {
    char *$GCINFO;
    int $class_id;
    $SuperG_class $superclass;
    B_NoneType (*__init__) (deactQ_L_33Cont, $Cont, deactQ_main);
    void (*__serialize__) (deactQ_L_33Cont, $Serial$state);
    deactQ_L_33Cont (*__deserialize__) (deactQ_L_33Cont, $Serial$state);
    B_bool (*__bool__) (deactQ_L_33Cont);
    B_str (*__str__) (deactQ_L_33Cont);
    B_str (*__repr__) (deactQ_L_33Cont);
    $R (*__call__) (deactQ_L_33Cont, B_NoneType);
};
struct deactQ_L_33Cont {
    struct deactQ_L_33ContG_class *$class;
    $Cont C_cont;
    deactQ_main G_act;
};
struct deactQ_L_34procG_class {
    char *$GCINFO;
    int $class_id;
    $SuperG_class $superclass;
    B_NoneType (*__init__) (deactQ_L_34proc, deactQ_main, B_Env);
    void (*__serialize__) (deactQ_L_34proc, $Serial$state);
    deactQ_L_34proc (*__deserialize__) (deactQ_L_34proc, $Serial$state);
    B_bool (*__bool__) (deactQ_L_34proc);
    B_str (*__str__) (deactQ_L_34proc);
    B_str (*__repr__) (deactQ_L_34proc);
    $R (*__call__) (deactQ_L_34proc, $Cont);
    $R (*__exec__) (deactQ_L_34proc, $Cont);
};
struct deactQ_L_34proc {
    struct deactQ_L_34procG_class *$class;
    deactQ_main G_act;
    B_Env env;
};
struct deactQ_ApaG_class {
    char *$GCINFO;
    int $class_id;
    $SuperG_class $superclass;
    $R (*__init__) (deactQ_Apa, $Cont);
    void (*__serialize__) (deactQ_Apa, $Serial$state);
    deactQ_Apa (*__deserialize__) (deactQ_Apa, $Serial$state);
    B_bool (*__bool__) (deactQ_Apa);
    B_str (*__str__) (deactQ_Apa);
    B_str (*__repr__) (deactQ_Apa);
    B_NoneType (*__resume__) (deactQ_Apa);
    B_NoneType (*__cleanup__) (deactQ_Apa);
    $R (*setupG_local) (deactQ_Apa, $Cont, $proc);
    $R (*computeG_local) (deactQ_Apa, $Cont, $action);
    $R (*noticeG_local) (deactQ_Apa, $Cont, B_int);
    B_Msg (*setup) (deactQ_Apa, $proc);
    B_Msg (*compute) (deactQ_Apa, $action);
    B_Msg (*notice) (deactQ_Apa, B_int);
};
struct deactQ_Apa {
    struct deactQ_ApaG_class *$class;
    $Actor $next;
    B_Msg $msg;
    B_Msg $msg_tail;
    $Lock $msg_lock;
    $int64 $affinity;
    B_Msg $outgoing;
    B_Msg $waitsfor;
    $int64 $consume_hd;
    $Catcher $catcher;
    $long $globkey;
};
struct deactQ_BepaG_class {
    char *$GCINFO;
    int $class_id;
    $SuperG_class $superclass;
    $R (*__init__) (deactQ_Bepa, $Cont);
    void (*__serialize__) (deactQ_Bepa, $Serial$state);
    deactQ_Bepa (*__deserialize__) (deactQ_Bepa, $Serial$state);
    B_bool (*__bool__) (deactQ_Bepa);
    B_str (*__str__) (deactQ_Bepa);
    B_str (*__repr__) (deactQ_Bepa);
    B_NoneType (*__resume__) (deactQ_Bepa);
    B_NoneType (*__cleanup__) (deactQ_Bepa);
    $R (*callbackG_local) (deactQ_Bepa, $Cont, B_int);
    B_Msg (*callback) (deactQ_Bepa, B_int);
};
struct deactQ_Bepa {
    struct deactQ_BepaG_class *$class;
    $Actor $next;
    B_Msg $msg;
    B_Msg $msg_tail;
    $Lock $msg_lock;
    $int64 $affinity;
    B_Msg $outgoing;
    B_Msg $waitsfor;
    $int64 $consume_hd;
    $Catcher $catcher;
    $long $globkey;
};
struct deactQ_mainG_class {
    char *$GCINFO;
    int $class_id;
    $SuperG_class $superclass;
    $R (*__init__) (deactQ_main, $Cont, B_Env);
    void (*__serialize__) (deactQ_main, $Serial$state);
    deactQ_main (*__deserialize__) (deactQ_main, $Serial$state);
    B_bool (*__bool__) (deactQ_main);
    B_str (*__str__) (deactQ_main);
    B_str (*__repr__) (deactQ_main);
    B_NoneType (*__resume__) (deactQ_main);
    B_NoneType (*__cleanup__) (deactQ_main);
    $R (*myprocG_local) (deactQ_main, $Cont, B_int);
    B_Msg (*myproc) (deactQ_main, B_int);
};
struct deactQ_main {
    struct deactQ_mainG_class *$class;
    $Actor $next;
    B_Msg $msg;
    B_Msg $msg_tail;
    $Lock $msg_lock;
    $int64 $affinity;
    B_Msg $outgoing;
    B_Msg $waitsfor;
    $int64 $consume_hd;
    $Catcher $catcher;
    $long $globkey;
    B_Env env;
    deactQ_Apa a;
    deactQ_Bepa b;
    B_Msg x;
    B_int r;
};
$R deactQ_ApaG_newact ($Cont);
$R deactQ_BepaG_newact ($Cont);
$R deactQ_mainG_newact ($Cont, B_Env);
extern struct deactQ_L_2ContG_class deactQ_L_2ContG_methods;
deactQ_L_2Cont deactQ_L_2ContG_new($Cont);
extern struct deactQ_L_4procG_class deactQ_L_4procG_methods;
deactQ_L_4proc deactQ_L_4procG_new(deactQ_Apa);
extern struct deactQ_L_6ContG_class deactQ_L_6ContG_methods;
deactQ_L_6Cont deactQ_L_6ContG_new($Cont);
extern struct deactQ_L_8ContG_class deactQ_L_8ContG_methods;
deactQ_L_8Cont deactQ_L_8ContG_new($action, $Cont);
extern struct deactQ_L_9procG_class deactQ_L_9procG_methods;
deactQ_L_9proc deactQ_L_9procG_new(deactQ_Apa, $proc);
extern struct deactQ_L_10procG_class deactQ_L_10procG_methods;
deactQ_L_10proc deactQ_L_10procG_new(deactQ_Apa, $action);
extern struct deactQ_L_11procG_class deactQ_L_11procG_methods;
deactQ_L_11proc deactQ_L_11procG_new(deactQ_Apa, B_int);
extern struct deactQ_L_12procG_class deactQ_L_12procG_methods;
deactQ_L_12proc deactQ_L_12procG_new(deactQ_Bepa, B_int);
extern struct deactQ_L_16actionG_class deactQ_L_16actionG_methods;
deactQ_L_16action deactQ_L_16actionG_new(deactQ_Apa);
extern struct deactQ_L_18actionG_class deactQ_L_18actionG_methods;
deactQ_L_18action deactQ_L_18actionG_new(deactQ_Bepa);
extern struct deactQ_L_21actionG_class deactQ_L_21actionG_methods;
deactQ_L_21action deactQ_L_21actionG_new(deactQ_main);
extern struct deactQ_L_22ContG_class deactQ_L_22ContG_methods;
deactQ_L_22Cont deactQ_L_22ContG_new(deactQ_main, $Cont);
extern struct deactQ_L_23ContG_class deactQ_L_23ContG_methods;
deactQ_L_23Cont deactQ_L_23ContG_new(deactQ_main, $Cont);
extern struct deactQ_L_24ContG_class deactQ_L_24ContG_methods;
deactQ_L_24Cont deactQ_L_24ContG_new(deactQ_main, $Cont);
extern struct deactQ_L_25procG_class deactQ_L_25procG_methods;
deactQ_L_25proc deactQ_L_25procG_new(deactQ_main, B_int);
extern struct deactQ_L_27ContG_class deactQ_L_27ContG_methods;
deactQ_L_27Cont deactQ_L_27ContG_new($Cont, deactQ_Apa);
extern struct deactQ_L_28procG_class deactQ_L_28procG_methods;
deactQ_L_28proc deactQ_L_28procG_new(deactQ_Apa);
extern struct deactQ_L_30ContG_class deactQ_L_30ContG_methods;
deactQ_L_30Cont deactQ_L_30ContG_new($Cont, deactQ_Bepa);
extern struct deactQ_L_31procG_class deactQ_L_31procG_methods;
deactQ_L_31proc deactQ_L_31procG_new(deactQ_Bepa);
extern struct deactQ_L_33ContG_class deactQ_L_33ContG_methods;
deactQ_L_33Cont deactQ_L_33ContG_new($Cont, deactQ_main);
extern struct deactQ_L_34procG_class deactQ_L_34procG_methods;
deactQ_L_34proc deactQ_L_34procG_new(deactQ_main, B_Env);
extern struct deactQ_ApaG_class deactQ_ApaG_methods;
$R deactQ_ApaG_new($Cont);
extern struct deactQ_BepaG_class deactQ_BepaG_methods;
$R deactQ_BepaG_new($Cont);
extern struct deactQ_mainG_class deactQ_mainG_methods;
$R deactQ_mainG_new($Cont, B_Env);
void deactQ___init__ ();