/* Acton source hash: test-hash */
#pragma once
#include "builtin/builtin.h"
#include "rts/rts.h"
struct linesQ_L_2Cont;
struct linesQ_L_4action;
struct linesQ_L_6Cont;
struct linesQ_L_7proc;
struct linesQ_L_8proc;
struct linesQ_L_9proc;
struct linesQ_L_10proc;
struct linesQ_L_14action;
struct linesQ_L_16action;
struct linesQ_L_19action;
struct linesQ_L_20proc;
struct linesQ_L_21Cont;
struct linesQ_L_22Cont;
struct linesQ_L_23Cont;
struct linesQ_L_24proc;
struct linesQ_L_25proc;
struct linesQ_L_27Cont;
struct linesQ_L_28proc;
struct linesQ_L_30Cont;
struct linesQ_L_31proc;
struct linesQ_L_33Cont;
struct linesQ_L_34proc;
struct linesQ_Apa;
struct linesQ_Bepa;
struct linesQ_main;
typedef struct linesQ_L_2Cont *linesQ_L_2Cont;
typedef struct linesQ_L_4action *linesQ_L_4action;
typedef struct linesQ_L_6Cont *linesQ_L_6Cont;
typedef struct linesQ_L_7proc *linesQ_L_7proc;
typedef struct linesQ_L_8proc *linesQ_L_8proc;
typedef struct linesQ_L_9proc *linesQ_L_9proc;
typedef struct linesQ_L_10proc *linesQ_L_10proc;
typedef struct linesQ_L_14action *linesQ_L_14action;
typedef struct linesQ_L_16action *linesQ_L_16action;
typedef struct linesQ_L_19action *linesQ_L_19action;
typedef struct linesQ_L_20proc *linesQ_L_20proc;
typedef struct linesQ_L_21Cont *linesQ_L_21Cont;
typedef struct linesQ_L_22Cont *linesQ_L_22Cont;
typedef struct linesQ_L_23Cont *linesQ_L_23Cont;
typedef struct linesQ_L_24proc *linesQ_L_24proc;
typedef struct linesQ_L_25proc *linesQ_L_25proc;
typedef struct linesQ_L_27Cont *linesQ_L_27Cont;
typedef struct linesQ_L_28proc *linesQ_L_28proc;
typedef struct linesQ_L_30Cont *linesQ_L_30Cont;
typedef struct linesQ_L_31proc *linesQ_L_31proc;
typedef struct linesQ_L_33Cont *linesQ_L_33Cont;
typedef struct linesQ_L_34proc *linesQ_L_34proc;
typedef struct linesQ_Apa *linesQ_Apa;
typedef struct linesQ_Bepa *linesQ_Bepa;
typedef struct linesQ_main *linesQ_main;
$R linesQ_L_1C_1cont (linesQ_Apa, $Cont, B_NoneType);
struct linesQ_L_2ContG_class {
    char *$GCINFO;
    int $class_id;
    $SuperG_class $superclass;
    B_NoneType (*__init__) (linesQ_L_2Cont, linesQ_Apa, $Cont);
    void (*__serialize__) (linesQ_L_2Cont, $Serial$state);
    linesQ_L_2Cont (*__deserialize__) (linesQ_L_2Cont, $Serial$state);
    B_bool (*__bool__) (linesQ_L_2Cont);
    B_str (*__str__) (linesQ_L_2Cont);
    B_str (*__repr__) (linesQ_L_2Cont);
    $R (*__call__) (linesQ_L_2Cont, B_NoneType);
};
struct linesQ_L_2Cont {
    struct linesQ_L_2ContG_class *$class;
    linesQ_Apa self;
    $Cont C_cont;
};
struct linesQ_L_4actionG_class {
    char *$GCINFO;
    int $class_id;
    $SuperG_class $superclass;
    B_NoneType (*__init__) (linesQ_L_4action, linesQ_Apa);
    void (*__serialize__) (linesQ_L_4action, $Serial$state);
    linesQ_L_4action (*__deserialize__) (linesQ_L_4action, $Serial$state);
    B_bool (*__bool__) (linesQ_L_4action);
    B_str (*__str__) (linesQ_L_4action);
    B_str (*__repr__) (linesQ_L_4action);
    $R (*__call__) (linesQ_L_4action, $Cont, B_int);
    $R (*__exec__) (linesQ_L_4action, $Cont, B_int);
    B_Msg (*__asyn__) (linesQ_L_4action, B_int);
};
struct linesQ_L_4action {
    struct linesQ_L_4actionG_class *$class;
    linesQ_Apa L_3obj;
};
$R linesQ_L_5C_3cont ($action, $Cont, B_int);
struct linesQ_L_6ContG_class {
    char *$GCINFO;
    int $class_id;
    $SuperG_class $superclass;
    B_NoneType (*__init__) (linesQ_L_6Cont, $action, $Cont);
    void (*__serialize__) (linesQ_L_6Cont, $Serial$state);
    linesQ_L_6Cont (*__deserialize__) (linesQ_L_6Cont, $Serial$state);
    B_bool (*__bool__) (linesQ_L_6Cont);
    B_str (*__str__) (linesQ_L_6Cont);
    B_str (*__repr__) (linesQ_L_6Cont);
    $R (*__call__) (linesQ_L_6Cont, B_int);
};
struct linesQ_L_6Cont {
    struct linesQ_L_6ContG_class *$class;
    $action cb;
    $Cont C_cont;
};
struct linesQ_L_7procG_class {
    char *$GCINFO;
    int $class_id;
    $SuperG_class $superclass;
    B_NoneType (*__init__) (linesQ_L_7proc, linesQ_Apa, $action);
    void (*__serialize__) (linesQ_L_7proc, $Serial$state);
    linesQ_L_7proc (*__deserialize__) (linesQ_L_7proc, $Serial$state);
    B_bool (*__bool__) (linesQ_L_7proc);
    B_str (*__str__) (linesQ_L_7proc);
    B_str (*__repr__) (linesQ_L_7proc);
    $R (*__call__) (linesQ_L_7proc, $Cont);
    $R (*__exec__) (linesQ_L_7proc, $Cont);
};
struct linesQ_L_7proc {
    struct linesQ_L_7procG_class *$class;
    linesQ_Apa self;
    $action cb;
};
struct linesQ_L_8procG_class {
    char *$GCINFO;
    int $class_id;
    $SuperG_class $superclass;
    B_NoneType (*__init__) (linesQ_L_8proc, linesQ_Apa, $action);
    void (*__serialize__) (linesQ_L_8proc, $Serial$state);
    linesQ_L_8proc (*__deserialize__) (linesQ_L_8proc, $Serial$state);
    B_bool (*__bool__) (linesQ_L_8proc);
    B_str (*__str__) (linesQ_L_8proc);
    B_str (*__repr__) (linesQ_L_8proc);
    $R (*__call__) (linesQ_L_8proc, $Cont);
    $R (*__exec__) (linesQ_L_8proc, $Cont);
};
struct linesQ_L_8proc {
    struct linesQ_L_8procG_class *$class;
    linesQ_Apa self;
    $action cb;
};
struct linesQ_L_9procG_class {
    char *$GCINFO;
    int $class_id;
    $SuperG_class $superclass;
    B_NoneType (*__init__) (linesQ_L_9proc, linesQ_Apa, B_int);
    void (*__serialize__) (linesQ_L_9proc, $Serial$state);
    linesQ_L_9proc (*__deserialize__) (linesQ_L_9proc, $Serial$state);
    B_bool (*__bool__) (linesQ_L_9proc);
    B_str (*__str__) (linesQ_L_9proc);
    B_str (*__repr__) (linesQ_L_9proc);
    $R (*__call__) (linesQ_L_9proc, $Cont);
    $R (*__exec__) (linesQ_L_9proc, $Cont);
};
struct linesQ_L_9proc {
    struct linesQ_L_9procG_class *$class;
    linesQ_Apa self;
    B_int i;
};
struct linesQ_L_10procG_class {
    char *$GCINFO;
    int $class_id;
    $SuperG_class $superclass;
    B_NoneType (*__init__) (linesQ_L_10proc, linesQ_Bepa, B_int);
    void (*__serialize__) (linesQ_L_10proc, $Serial$state);
    linesQ_L_10proc (*__deserialize__) (linesQ_L_10proc, $Serial$state);
    B_bool (*__bool__) (linesQ_L_10proc);
    B_str (*__str__) (linesQ_L_10proc);
    B_str (*__repr__) (linesQ_L_10proc);
    $R (*__call__) (linesQ_L_10proc, $Cont);
    $R (*__exec__) (linesQ_L_10proc, $Cont);
};
struct linesQ_L_10proc {
    struct linesQ_L_10procG_class *$class;
    linesQ_Bepa self;
    B_int i;
};
struct linesQ_L_14actionG_class {
    char *$GCINFO;
    int $class_id;
    $SuperG_class $superclass;
    B_NoneType (*__init__) (linesQ_L_14action, linesQ_Apa);
    void (*__serialize__) (linesQ_L_14action, $Serial$state);
    linesQ_L_14action (*__deserialize__) (linesQ_L_14action, $Serial$state);
    B_bool (*__bool__) (linesQ_L_14action);
    B_str (*__str__) (linesQ_L_14action);
    B_str (*__repr__) (linesQ_L_14action);
    $R (*__call__) (linesQ_L_14action, $Cont, B_int);
    $R (*__exec__) (linesQ_L_14action, $Cont, B_int);
    B_Msg (*__asyn__) (linesQ_L_14action, B_int);
};
struct linesQ_L_14action {
    struct linesQ_L_14actionG_class *$class;
    linesQ_Apa L_13obj;
};
struct linesQ_L_16actionG_class {
    char *$GCINFO;
    int $class_id;
    $SuperG_class $superclass;
    B_NoneType (*__init__) (linesQ_L_16action, linesQ_Bepa);
    void (*__serialize__) (linesQ_L_16action, $Serial$state);
    linesQ_L_16action (*__deserialize__) (linesQ_L_16action, $Serial$state);
    B_bool (*__bool__) (linesQ_L_16action);
    B_str (*__str__) (linesQ_L_16action);
    B_str (*__repr__) (linesQ_L_16action);
    $R (*__call__) (linesQ_L_16action, $Cont, B_int);
    $R (*__exec__) (linesQ_L_16action, $Cont, B_int);
    B_Msg (*__asyn__) (linesQ_L_16action, B_int);
};
struct linesQ_L_16action {
    struct linesQ_L_16actionG_class *$class;
    linesQ_Bepa L_15obj;
};
struct linesQ_L_19actionG_class {
    char *$GCINFO;
    int $class_id;
    $SuperG_class $superclass;
    B_NoneType (*__init__) (linesQ_L_19action, linesQ_main);
    void (*__serialize__) (linesQ_L_19action, $Serial$state);
    linesQ_L_19action (*__deserialize__) (linesQ_L_19action, $Serial$state);
    B_bool (*__bool__) (linesQ_L_19action);
    B_str (*__str__) (linesQ_L_19action);
    B_str (*__repr__) (linesQ_L_19action);
    $R (*__call__) (linesQ_L_19action, $Cont, B_int);
    $R (*__exec__) (linesQ_L_19action, $Cont, B_int);
    B_Msg (*__asyn__) (linesQ_L_19action, B_int);
};
struct linesQ_L_19action {
    struct linesQ_L_19actionG_class *$class;
    linesQ_main L_18obj;
};
struct linesQ_L_20procG_class {
    char *$GCINFO;
    int $class_id;
    $SuperG_class $superclass;
    B_NoneType (*__init__) (linesQ_L_20proc, linesQ_main);
    void (*__serialize__) (linesQ_L_20proc, $Serial$state);
    linesQ_L_20proc (*__deserialize__) (linesQ_L_20proc, $Serial$state);
    B_bool (*__bool__) (linesQ_L_20proc);
    B_str (*__str__) (linesQ_L_20proc);
    B_str (*__repr__) (linesQ_L_20proc);
    $R (*__call__) (linesQ_L_20proc, $Cont);
    $R (*__exec__) (linesQ_L_20proc, $Cont);
};
struct linesQ_L_20proc {
    struct linesQ_L_20procG_class *$class;
    linesQ_main self;
};
$R linesQ_L_17C_9cont (linesQ_main, B_Iterable, B_Number, $Cont, B_int);
struct linesQ_L_21ContG_class {
    char *$GCINFO;
    int $class_id;
    $SuperG_class $superclass;
    B_NoneType (*__init__) (linesQ_L_21Cont, linesQ_main, B_Iterable, B_Number, $Cont);
    void (*__serialize__) (linesQ_L_21Cont, $Serial$state);
    linesQ_L_21Cont (*__deserialize__) (linesQ_L_21Cont, $Serial$state);
    B_bool (*__bool__) (linesQ_L_21Cont);
    B_str (*__str__) (linesQ_L_21Cont);
    B_str (*__repr__) (linesQ_L_21Cont);
    $R (*__call__) (linesQ_L_21Cont, B_int);
};
struct linesQ_L_21Cont {
    struct linesQ_L_21ContG_class *$class;
    linesQ_main self;
    B_Iterable W_1909;
    B_Number W_2124;
    $Cont C_cont;
};
$R linesQ_L_12C_7cont (linesQ_main, B_Iterable, B_Number, $Cont, linesQ_Bepa);
struct linesQ_L_22ContG_class {
    char *$GCINFO;
    int $class_id;
    $SuperG_class $superclass;
    B_NoneType (*__init__) (linesQ_L_22Cont, linesQ_main, B_Iterable, B_Number, $Cont);
    void (*__serialize__) (linesQ_L_22Cont, $Serial$state);
    linesQ_L_22Cont (*__deserialize__) (linesQ_L_22Cont, $Serial$state);
    B_bool (*__bool__) (linesQ_L_22Cont);
    B_str (*__str__) (linesQ_L_22Cont);
    B_str (*__repr__) (linesQ_L_22Cont);
    $R (*__call__) (linesQ_L_22Cont, linesQ_Bepa);
};
struct linesQ_L_22Cont {
    struct linesQ_L_22ContG_class *$class;
    linesQ_main self;
    B_Iterable W_1909;
    B_Number W_2124;
    $Cont C_cont;
};
$R linesQ_L_11C_5cont (linesQ_main, B_Iterable, B_Number, $Cont, linesQ_Apa);
struct linesQ_L_23ContG_class {
    char *$GCINFO;
    int $class_id;
    $SuperG_class $superclass;
    B_NoneType (*__init__) (linesQ_L_23Cont, linesQ_main, B_Iterable, B_Number, $Cont);
    void (*__serialize__) (linesQ_L_23Cont, $Serial$state);
    linesQ_L_23Cont (*__deserialize__) (linesQ_L_23Cont, $Serial$state);
    B_bool (*__bool__) (linesQ_L_23Cont);
    B_str (*__str__) (linesQ_L_23Cont);
    B_str (*__repr__) (linesQ_L_23Cont);
    $R (*__call__) (linesQ_L_23Cont, linesQ_Apa);
};
struct linesQ_L_23Cont {
    struct linesQ_L_23ContG_class *$class;
    linesQ_main self;
    B_Iterable W_1909;
    B_Number W_2124;
    $Cont C_cont;
};
struct linesQ_L_24procG_class {
    char *$GCINFO;
    int $class_id;
    $SuperG_class $superclass;
    B_NoneType (*__init__) (linesQ_L_24proc, linesQ_main, B_int);
    void (*__serialize__) (linesQ_L_24proc, $Serial$state);
    linesQ_L_24proc (*__deserialize__) (linesQ_L_24proc, $Serial$state);
    B_bool (*__bool__) (linesQ_L_24proc);
    B_str (*__str__) (linesQ_L_24proc);
    B_str (*__repr__) (linesQ_L_24proc);
    $R (*__call__) (linesQ_L_24proc, $Cont);
    $R (*__exec__) (linesQ_L_24proc, $Cont);
};
struct linesQ_L_24proc {
    struct linesQ_L_24procG_class *$class;
    linesQ_main self;
    B_int i;
};
struct linesQ_L_25procG_class {
    char *$GCINFO;
    int $class_id;
    $SuperG_class $superclass;
    B_NoneType (*__init__) (linesQ_L_25proc, linesQ_main);
    void (*__serialize__) (linesQ_L_25proc, $Serial$state);
    linesQ_L_25proc (*__deserialize__) (linesQ_L_25proc, $Serial$state);
    B_bool (*__bool__) (linesQ_L_25proc);
    B_str (*__str__) (linesQ_L_25proc);
    B_str (*__repr__) (linesQ_L_25proc);
    $R (*__call__) (linesQ_L_25proc, $Cont);
    $R (*__exec__) (linesQ_L_25proc, $Cont);
};
struct linesQ_L_25proc {
    struct linesQ_L_25procG_class *$class;
    linesQ_main self;
};
$R linesQ_L_26C_11cont ($Cont, linesQ_Apa, B_NoneType);
struct linesQ_L_27ContG_class {
    char *$GCINFO;
    int $class_id;
    $SuperG_class $superclass;
    B_NoneType (*__init__) (linesQ_L_27Cont, $Cont, linesQ_Apa);
    void (*__serialize__) (linesQ_L_27Cont, $Serial$state);
    linesQ_L_27Cont (*__deserialize__) (linesQ_L_27Cont, $Serial$state);
    B_bool (*__bool__) (linesQ_L_27Cont);
    B_str (*__str__) (linesQ_L_27Cont);
    B_str (*__repr__) (linesQ_L_27Cont);
    $R (*__call__) (linesQ_L_27Cont, B_NoneType);
};
struct linesQ_L_27Cont {
    struct linesQ_L_27ContG_class *$class;
    $Cont C_cont;
    linesQ_Apa G_act;
};
struct linesQ_L_28procG_class {
    char *$GCINFO;
    int $class_id;
    $SuperG_class $superclass;
    B_NoneType (*__init__) (linesQ_L_28proc, linesQ_Apa);
    void (*__serialize__) (linesQ_L_28proc, $Serial$state);
    linesQ_L_28proc (*__deserialize__) (linesQ_L_28proc, $Serial$state);
    B_bool (*__bool__) (linesQ_L_28proc);
    B_str (*__str__) (linesQ_L_28proc);
    B_str (*__repr__) (linesQ_L_28proc);
    $R (*__call__) (linesQ_L_28proc, $Cont);
    $R (*__exec__) (linesQ_L_28proc, $Cont);
};
struct linesQ_L_28proc {
    struct linesQ_L_28procG_class *$class;
    linesQ_Apa G_act;
};
$R linesQ_L_29C_13cont ($Cont, linesQ_Bepa, B_NoneType);
struct linesQ_L_30ContG_class {
    char *$GCINFO;
    int $class_id;
    $SuperG_class $superclass;
    B_NoneType (*__init__) (linesQ_L_30Cont, $Cont, linesQ_Bepa);
    void (*__serialize__) (linesQ_L_30Cont, $Serial$state);
    linesQ_L_30Cont (*__deserialize__) (linesQ_L_30Cont, $Serial$state);
    B_bool (*__bool__) (linesQ_L_30Cont);
    B_str (*__str__) (linesQ_L_30Cont);
    B_str (*__repr__) (linesQ_L_30Cont);
    $R (*__call__) (linesQ_L_30Cont, B_NoneType);
};
struct linesQ_L_30Cont {
    struct linesQ_L_30ContG_class *$class;
    $Cont C_cont;
    linesQ_Bepa G_act;
};
struct linesQ_L_31procG_class {
    char *$GCINFO;
    int $class_id;
    $SuperG_class $superclass;
    B_NoneType (*__init__) (linesQ_L_31proc, linesQ_Bepa);
    void (*__serialize__) (linesQ_L_31proc, $Serial$state);
    linesQ_L_31proc (*__deserialize__) (linesQ_L_31proc, $Serial$state);
    B_bool (*__bool__) (linesQ_L_31proc);
    B_str (*__str__) (linesQ_L_31proc);
    B_str (*__repr__) (linesQ_L_31proc);
    $R (*__call__) (linesQ_L_31proc, $Cont);
    $R (*__exec__) (linesQ_L_31proc, $Cont);
};
struct linesQ_L_31proc {
    struct linesQ_L_31procG_class *$class;
    linesQ_Bepa G_act;
};
$R linesQ_L_32C_15cont ($Cont, linesQ_main, B_NoneType);
struct linesQ_L_33ContG_class {
    char *$GCINFO;
    int $class_id;
    $SuperG_class $superclass;
    B_NoneType (*__init__) (linesQ_L_33Cont, $Cont, linesQ_main);
    void (*__serialize__) (linesQ_L_33Cont, $Serial$state);
    linesQ_L_33Cont (*__deserialize__) (linesQ_L_33Cont, $Serial$state);
    B_bool (*__bool__) (linesQ_L_33Cont);
    B_str (*__str__) (linesQ_L_33Cont);
    B_str (*__repr__) (linesQ_L_33Cont);
    $R (*__call__) (linesQ_L_33Cont, B_NoneType);
};
struct linesQ_L_33Cont {
    struct linesQ_L_33ContG_class *$class;
    $Cont C_cont;
    linesQ_main G_act;
};
struct linesQ_L_34procG_class {
    char *$GCINFO;
    int $class_id;
    $SuperG_class $superclass;
    B_NoneType (*__init__) (linesQ_L_34proc, linesQ_main, B_Env);
    void (*__serialize__) (linesQ_L_34proc, $Serial$state);
    linesQ_L_34proc (*__deserialize__) (linesQ_L_34proc, $Serial$state);
    B_bool (*__bool__) (linesQ_L_34proc);
    B_str (*__str__) (linesQ_L_34proc);
    B_str (*__repr__) (linesQ_L_34proc);
    $R (*__call__) (linesQ_L_34proc, $Cont);
    $R (*__exec__) (linesQ_L_34proc, $Cont);
};
struct linesQ_L_34proc {
    struct linesQ_L_34procG_class *$class;
    linesQ_main G_act;
    B_Env env;
};
struct linesQ_ApaG_class {
    char *$GCINFO;
    int $class_id;
    $SuperG_class $superclass;
    $R (*__init__) (linesQ_Apa, $Cont);
    void (*__serialize__) (linesQ_Apa, $Serial$state);
    linesQ_Apa (*__deserialize__) (linesQ_Apa, $Serial$state);
    B_bool (*__bool__) (linesQ_Apa);
    B_str (*__str__) (linesQ_Apa);
    B_str (*__repr__) (linesQ_Apa);
    B_NoneType (*__resume__) (linesQ_Apa);
    B_NoneType (*__cleanup__) (linesQ_Apa);
    $R (*setupG_local) (linesQ_Apa, $Cont, $action);
    $R (*computeG_local) (linesQ_Apa, $Cont, $action);
    $R (*noticeG_local) (linesQ_Apa, $Cont, B_int);
    B_Msg (*setup) (linesQ_Apa, $action);
    B_Msg (*compute) (linesQ_Apa, $action);
    B_Msg (*notice) (linesQ_Apa, B_int);
};
struct linesQ_Apa {
    struct linesQ_ApaG_class *$class;
    $Actor $next;
    B_Msg $msg;
    B_Msg $msg_tail;
    $Lock $msg_lock;
    $int64 $affinity;
    B_Msg $outgoing;
    B_Msg $waitsfor;
    $int64 $consume_hd;
    $Catcher $catcher;
    $long $globkey;
    B_int apa;
    B_int apb;
    B_int y;
    B_int z;
};
struct linesQ_BepaG_class {
    char *$GCINFO;
    int $class_id;
    $SuperG_class $superclass;
    $R (*__init__) (linesQ_Bepa, $Cont);
    void (*__serialize__) (linesQ_Bepa, $Serial$state);
    linesQ_Bepa (*__deserialize__) (linesQ_Bepa, $Serial$state);
    B_bool (*__bool__) (linesQ_Bepa);
    B_str (*__str__) (linesQ_Bepa);
    B_str (*__repr__) (linesQ_Bepa);
    B_NoneType (*__resume__) (linesQ_Bepa);
    B_NoneType (*__cleanup__) (linesQ_Bepa);
    $R (*callbackG_local) (linesQ_Bepa, $Cont, B_int);
    B_Msg (*callback) (linesQ_Bepa, B_int);
};
struct linesQ_Bepa {
    struct linesQ_BepaG_class *$class;
    $Actor $next;
    B_Msg $msg;
    B_Msg $msg_tail;
    $Lock $msg_lock;
    $int64 $affinity;
    B_Msg $outgoing;
    B_Msg $waitsfor;
    $int64 $consume_hd;
    $Catcher $catcher;
    $long $globkey;
};
struct linesQ_mainG_class {
    char *$GCINFO;
    int $class_id;
    $SuperG_class $superclass;
    $R (*__init__) (linesQ_main, $Cont, B_Env);
    void (*__serialize__) (linesQ_main, $Serial$state);
    linesQ_main (*__deserialize__) (linesQ_main, $Serial$state);
    B_bool (*__bool__) (linesQ_main);
    B_str (*__str__) (linesQ_main);
    B_str (*__repr__) (linesQ_main);
    B_NoneType (*__resume__) (linesQ_main);
    B_NoneType (*__cleanup__) (linesQ_main);
    $R (*myprocG_local) (linesQ_main, $Cont, B_int);
    $R (*nopG_local) (linesQ_main, $Cont);
    B_Msg (*myproc) (linesQ_main, B_int);
    B_Msg (*nop) (linesQ_main);
};
struct linesQ_main {
    struct linesQ_mainG_class *$class;
    $Actor $next;
    B_Msg $msg;
    B_Msg $msg_tail;
    $Lock $msg_lock;
    $int64 $affinity;
    B_Msg $outgoing;
    B_Msg $waitsfor;
    $int64 $consume_hd;
    $Catcher $catcher;
    $long $globkey;
    B_Env env;
    linesQ_Apa a;
    linesQ_Bepa b;
    B_Msg x;
    B_int r;
    B_int v;
    B_int i;
};
$R linesQ_ApaG_newact ($Cont);
$R linesQ_BepaG_newact ($Cont);
$R linesQ_mainG_newact ($Cont, B_Env);
extern struct linesQ_L_2ContG_class linesQ_L_2ContG_methods;
linesQ_L_2Cont linesQ_L_2ContG_new(linesQ_Apa, $Cont);
extern struct linesQ_L_4actionG_class linesQ_L_4actionG_methods;
linesQ_L_4action linesQ_L_4actionG_new(linesQ_Apa);
extern struct linesQ_L_6ContG_class linesQ_L_6ContG_methods;
linesQ_L_6Cont linesQ_L_6ContG_new($action, $Cont);
extern struct linesQ_L_7procG_class linesQ_L_7procG_methods;
linesQ_L_7proc linesQ_L_7procG_new(linesQ_Apa, $action);
extern struct linesQ_L_8procG_class linesQ_L_8procG_methods;
linesQ_L_8proc linesQ_L_8procG_new(linesQ_Apa, $action);
extern struct linesQ_L_9procG_class linesQ_L_9procG_methods;
linesQ_L_9proc linesQ_L_9procG_new(linesQ_Apa, B_int);
extern struct linesQ_L_10procG_class linesQ_L_10procG_methods;
linesQ_L_10proc linesQ_L_10procG_new(linesQ_Bepa, B_int);
extern struct linesQ_L_14actionG_class linesQ_L_14actionG_methods;
linesQ_L_14action linesQ_L_14actionG_new(linesQ_Apa);
extern struct linesQ_L_16actionG_class linesQ_L_16actionG_methods;
linesQ_L_16action linesQ_L_16actionG_new(linesQ_Bepa);
extern struct linesQ_L_19actionG_class linesQ_L_19actionG_methods;
linesQ_L_19action linesQ_L_19actionG_new(linesQ_main);
extern struct linesQ_L_20procG_class linesQ_L_20procG_methods;
linesQ_L_20proc linesQ_L_20procG_new(linesQ_main);
extern struct linesQ_L_21ContG_class linesQ_L_21ContG_methods;
linesQ_L_21Cont linesQ_L_21ContG_new(linesQ_main, B_Iterable, B_Number, $Cont);
extern struct linesQ_L_22ContG_class linesQ_L_22ContG_methods;
linesQ_L_22Cont linesQ_L_22ContG_new(linesQ_main, B_Iterable, B_Number, $Cont);
extern struct linesQ_L_23ContG_class linesQ_L_23ContG_methods;
linesQ_L_23Cont linesQ_L_23ContG_new(linesQ_main, B_Iterable, B_Number, $Cont);
extern struct linesQ_L_24procG_class linesQ_L_24procG_methods;
linesQ_L_24proc linesQ_L_24procG_new(linesQ_main, B_int);
extern struct linesQ_L_25procG_class linesQ_L_25procG_methods;
linesQ_L_25proc linesQ_L_25procG_new(linesQ_main);
extern struct linesQ_L_27ContG_class linesQ_L_27ContG_methods;
linesQ_L_27Cont linesQ_L_27ContG_new($Cont, linesQ_Apa);
extern struct linesQ_L_28procG_class linesQ_L_28procG_methods;
linesQ_L_28proc linesQ_L_28procG_new(linesQ_Apa);
extern struct linesQ_L_30ContG_class linesQ_L_30ContG_methods;
linesQ_L_30Cont linesQ_L_30ContG_new($Cont, linesQ_Bepa);
extern struct linesQ_L_31procG_class linesQ_L_31procG_methods;
linesQ_L_31proc linesQ_L_31procG_new(linesQ_Bepa);
extern struct linesQ_L_33ContG_class linesQ_L_33ContG_methods;
linesQ_L_33Cont linesQ_L_33ContG_new($Cont, linesQ_main);
extern struct linesQ_L_34procG_class linesQ_L_34procG_methods;
linesQ_L_34proc linesQ_L_34procG_new(linesQ_main, B_Env);
extern struct linesQ_ApaG_class linesQ_ApaG_methods;
$R linesQ_ApaG_new($Cont);
extern struct linesQ_BepaG_class linesQ_BepaG_methods;
$R linesQ_BepaG_new($Cont);
extern struct linesQ_mainG_class linesQ_mainG_methods;
$R linesQ_mainG_new($Cont, B_Env);
extern B_Number linesQ_W_19;
extern B_Times linesQ_W_238;
extern B_Plus linesQ_W_609;
extern B_Eq linesQ_W_784;
extern B_Ord linesQ_W_1216;
void linesQ___init__ ();