FROM debian:13
MAINTAINER Kristian Larsson <kristian@spritelink.net>

ARG TARGETARCH
COPY deb/acton_*${TARGETARCH}.deb /tmp/acton.deb

RUN apt-get update \
 && apt-get install -y --no-install-recommends /tmp/acton.deb \
 && rm /tmp/acton.deb \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*

ENTRYPOINT ["/usr/bin/acton"]
