all:
	cd lists && $(MAKE)
	cd hash && $(MAKE)
	cd iterator && $(MAKE)
	cd dicts && $(MAKE)
	cd sets && $(MAKE)

clean:
	cd lists && $(MAKE) clean
	cd hash && $(MAKE) clean
	cd iterator && $(MAKE) clean
	cd dicts && $(MAKE) clean
	cd sets && $(MAKE) clean

