module Acton.Builtin where

import Utils
import Acton.Syntax
    
selfKW                              = name "__self__"
initKW                              = name "__init__"
enterKW                             = name "__enter__"
exitKW                              = name "__exit__"
iterKW                              = name "iter"
nextKW                              = name "__next__"
containsKW                          = name "__contains__"
containsnotKW                       = name "__containsnot__"
getitemKW                           = name "__getitem__"
setitemKW                           = name "__setitem__"
getsliceKW                          = name "__getslice__"
setsliceKW                          = name "__setslice__"
boolKW                              = name "__bool__"

iaddKW                              = name "__iadd__"
isubKW                              = name "__isub__"
imulKW                              = name "__imul__"
ipowKW                              = name "__ipow__"
itruedivKW                          = name "__itruediv__"
imodKW                              = name "__imod__"
ifloordivKW                         = name "__ifloordiv__"
ilshiftKW                           = name "__ilshift__"
irshiftKW                           = name "__irshift__"
iorKW                               = name "__ior__"
ixorKW                              = name "__ixor__"
iandKW                              = name "__iand__"
imatmulKW                           = name "__imatmul__"

addKW                               = name "__add__"
subKW                               = name "__sub__"
mulKW                               = name "__mul__"
powKW                               = name "__pow__"
truedivKW                           = name "__truediv__"
modKW                               = name "__mod__"
floordivKW                          = name "__floordiv__"
lshiftKW                            = name "__lshift__"
rshiftKW                            = name "__rshift__"
orKW                                = name "__or__"
xorKW                               = name "__xor__"
andKW                               = name "__and__"
matmulKW                            = name "__matmul__"

posKW                               = name "__pos__"
negKW                               = name "__neg__"
invertKW                            = name "__invert__"

eqKW                                = name "__eq__"
neKW                                = name "__ne__"
ltKW                                = name "__lt__"
leKW                                = name "__le__"
gtKW                                = name "__gt__"
geKW                                = name "__ge__"
isKW                                = name "__is__"
isnotKW                             = name "__isnot__"

nBuiltin                            = name "__builtin__"
mBuiltin                            = ModName [nBuiltin]
qBuiltin n                          = QName mBuiltin n

nSequence                           = name "Sequence"
nMapping                            = name "Mapping"
nSet                                = name "Set"
nInt                                = name "int"
nFloat                              = name "float"
nBool                               = name "bool"
nStr                                = name "str"
nBytes                              = name "bytes"
nRef                                = name "Ref"
nMsg                                = name "Msg"
nException                          = name "Exception"
nBoolean                            = name "Boolean"
nIndexed                            = name "Indexed"
nSliceable                          = name "Sliceable"
nHashable                           = name "Hashable"
nPlus                               = name "Plus"
nMinus                              = name "Minus"
nNumber                             = name "Number"
nReal                               = name "Real"
nIntegral                           = name "Integral"
nLogical                            = name "Logical"
nMatrix                             = name "Matrix"
nEq                                 = name "Eq"
nOrd                                = name "Ord"
nIdentity                           = name "Identity"
nCollection                         = name "Collection"
nContainer                          = name "Container"
nIterable                           = name "Iterable"
nContextManager                     = name "ContextManager"
nObject                             = name "object"
nStopIteration                      = name "StopIteration"
nValueError                         = name "ValueError"
nShow                               = name "Show"
nLen                                = name "len"
nPrint                              = name "print"
nPostpone                           = name "postpone"
nDict                               = name "dict"
nList                               = name "list"
nSet'                               = name "set"

qnSequence                          = qBuiltin nSequence
qnMapping                           = qBuiltin nMapping
qnSet                               = qBuiltin nSet
qnInt                               = qBuiltin nInt
qnFloat                             = qBuiltin nFloat
qnBool                              = qBuiltin nBool
qnStr                               = qBuiltin nStr
qnBytes                             = qBuiltin nBytes
qnRef                               = qBuiltin nRef
qnMsg                               = qBuiltin nMsg
qnException                         = qBuiltin nException
qnBoolean                           = qBuiltin nBoolean
qnIndexed                           = qBuiltin nIndexed
qnSliceable                         = qBuiltin nSliceable
qHashable                           = qBuiltin nHashable
qnPlus                              = qBuiltin nPlus
qnMinus                             = qBuiltin nMinus
qnNumber                            = qBuiltin nNumber
qnReal                              = qBuiltin nReal
qnIntegral                          = qBuiltin nIntegral
qnLogical                           = qBuiltin nLogical
qnMatrix                            = qBuiltin nMatrix
qnEq                                = qBuiltin nEq
qnOrd                               = qBuiltin nOrd
qnIdentity                          = qBuiltin nIdentity
qnCollection                        = qBuiltin nCollection
qnContainer                         = qBuiltin nContainer
qnIterable                          = qBuiltin nIterable
qnContextManager                    = qBuiltin nContextManager
qnObject                            = qBuiltin nObject
qnStopIteration                     = qBuiltin nStopIteration
qnValueError                        = qBuiltin nValueError
qnShow                              = qBuiltin nShow
qnLen                               = qBuiltin nLen
qnPrint                             = qBuiltin nPrint
qnPostpone                          = qBuiltin nPostpone
qnDict                              = qBuiltin nDict
qnList                              = qBuiltin nList
qnSet'                              = qBuiltin nSet

cSequence a                         = TC qnSequence [a]
cMapping a b                        = TC qnMapping [a,b]
cSet a                              = TC qnSet [a]
cInt                                = TC qnInt []
cFloat                              = TC qnFloat []
cBool                               = TC qnBool []
cStr                                = TC qnStr []
cBytes                              = TC qnBytes []
cRef                                = TC qnRef []
cMsg a                              = TC qnMsg [a]
cException                          = TC qnException []
cBoolean                            = TC qnBoolean []
cIndexed a b                        = TC qnIndexed [a,b]
cSliceable                          = TC qnSliceable []
cHashable                           = TC qHashable []
cPlus                               = TC qnPlus []
cMinus                              = TC qnMinus []
cNumber                             = TC qnNumber []
cReal                               = TC qnReal []
cIntegral                           = TC qnIntegral []
cLogical                            = TC qnLogical []
cMatrix                             = TC qnMatrix []
cEq                                 = TC qnEq []
cOrd                                = TC qnOrd []
cIdentity                           = TC qnIdentity []
cCollection a                       = TC qnCollection [a]
cContainer a                        = TC qnContainer [a]
cIterable a                         = TC qnIterable [a]
cContextManager                     = TC qnContextManager []
cObject                             = TC qnObject []
cStopIteration                      = TC qnStopIteration []
cValueError                         = TC qnValueError []
cShow                               = TC qnShow []

pSequence a                         = tCon (cSequence a)
pMapping a b                        = tCon (cMapping a b)
pSet a                              = tCon (cSet a)
tInt                                = tCon cInt
tFloat                              = tCon cFloat
tBool                               = tCon cBool
tStr                                = tCon cStr
tBytes                              = tCon cBytes
tRef                                = tCon cRef
tMsg a                              = tCon (cMsg a)
tException                          = tCon cException
pBoolean                            = tCon cBoolean
pIndexed a b                        = tCon (cIndexed a b)
pSliceable                          = tCon cSliceable
pHashable                           = tCon cHashable
pPlus                               = tCon cPlus
pMinus                              = tCon cMinus
pNumber                             = tCon cNumber
pReal                               = tCon cReal
pIntegral                           = tCon cIntegral
pLogical                            = tCon cLogical
pMatrix                             = tCon cMatrix
pEq                                 = tCon cEq
pOrd                                = tCon cOrd
pIdentity                           = tCon cIdentity
pCollection a                       = tCon (cCollection a)
pContainer a                        = tCon (cContainer a)
pIterable a                         = tCon (cIterable a)
pContextManager                     = tCon cContextManager
tObject                             = tCon cObject
tStopIteration                      = tCon cStopIteration
tValueError                         = tCon cValueError
pShow                               = tCon cShow

tSeq                                = pSequence
tMapping                            = pMapping
tSet                                = pSet

uniLit t (ULit l)                   = t == tStr
uniLit t _                          = False

uniElem us u@(ULit l)               = u `elem` us || UCon qnStr `elem` us
uniElem us u                        = u `elem` us

uniCon us qn                        = qn `elem` uniCons && UCon qn `elem` us

uniCons                             = [qnInt, qnFloat, qnBool, qnStr]
