module Acton.Builtin where

import Utils
import Acton.Syntax
    
nSelf                               = name "__self__"

nBuiltin                            = name "__builtin__"
mBuiltin                            = ModName [nBuiltin]
qBuiltin n                          = QName mBuiltin n

nIterable                           = name "Iterable"
nSequence                           = name "Sequence"
nMapping                            = name "Mapping"
nSet                                = name "Set"
nInt                                = name "int"
nFloat                              = name "float"
nBool                               = name "bool"
nStr                                = name "str"
nRef                                = name "Ref"
nMsg                                = name "Msg"
nException                          = name "Exception"
nTruth                              = name "Truth"
nIndexed                            = name "Indexed"
nSliceable                          = name "Sliceable"
nPlus                               = name "Plus"
nMinus                              = name "Minus"
nNumber                             = name "Number"
nReal                               = name "Real"
nIntegral                           = name "Integral"
nLogical                            = name "Logical"
nMatrix                             = name "Matrix"
nEq                                 = name "Eq"
nOrd                                = name "Ord"
nIdentity                           = name "Identity"
nContainer                          = name "Container"
nContextManager                     = name "ContextManager"

qnIterable                          = qBuiltin nIterable
qnSequence                          = qBuiltin nSequence
qnMapping                           = qBuiltin nMapping
qnSet                               = qBuiltin nSet
qnInt                               = qBuiltin nInt
qnFloat                             = qBuiltin nFloat
qnBool                              = qBuiltin nBool
qnStr                               = qBuiltin nStr
qnRef                               = qBuiltin nRef
qnMsg                               = qBuiltin nMsg
qnException                         = qBuiltin nException
qnTruth                             = qBuiltin nTruth
qnIndexed                           = qBuiltin nIndexed
qnSliceable                         = qBuiltin nSliceable
qnPlus                              = qBuiltin nPlus
qnMinus                             = qBuiltin nMinus
qnNumber                            = qBuiltin nNumber
qnReal                              = qBuiltin nReal
qnIntegral                          = qBuiltin nIntegral
qnLogical                           = qBuiltin nLogical
qnMatrix                            = qBuiltin nMatrix
qnEq                                = qBuiltin nEq
qnOrd                               = qBuiltin nOrd
qnIdentity                          = qBuiltin nIdentity
qnContainer                         = qBuiltin nContainer
qnContextManager                    = qBuiltin nContextManager

cIterable a                         = TC qnIterable [a]
cSequence a                         = TC qnSequence [a]
cMapping a b                        = TC qnMapping [a,b]
cSet a                              = TC qnSet [a]
cInt                                = TC qnInt []
cFloat                              = TC qnFloat []
cBool                               = TC qnBool []
cStr                                = TC qnStr []
cRef                                = TC qnRef []
cMsg a                              = TC qnMsg [a]
cException                          = TC qnException []
cTruth                              = TC qnTruth []
cIndexed a b                        = TC qnIndexed [a,b]
cSliceable                          = TC qnSliceable []
cPlus                               = TC qnPlus []
cMinus                              = TC qnMinus []
cNumber                             = TC qnNumber []
cReal                               = TC qnReal []
cIntegral                           = TC qnIntegral []
cLogical                            = TC qnLogical []
cMatrix                             = TC qnMatrix []
cEq                                 = TC qnEq []
cOrd                                = TC qnOrd []
cIdentity                           = TC qnIdentity []
cContainer a                        = TC qnContainer [a]
cContextManager                     = TC qnContextManager []

pIterable a                         = tCon (cIterable a)
pSequence a                         = tCon (cSequence a)
pMapping a b                        = tCon (cMapping a b)
pSet a                              = tCon (cSet a)
tInt                                = tCon cInt
tFloat                              = tCon cFloat
tBool                               = tCon cBool
tStr                                = tCon cStr
tRef                                = tCon cRef
tMsg a                              = tCon (cMsg a)
tException                          = tCon cException
pTruth                              = tCon cTruth
pIndexed a b                        = tCon (cIndexed a b)
pSliceable                          = tCon cSliceable
pPlus                               = tCon cPlus
pMinus                              = tCon cMinus
pNumber                             = tCon cNumber
pReal                               = tCon cReal
pIntegral                           = tCon cIntegral
pLogical                            = tCon cLogical
pMatrix                             = tCon cMatrix
pEq                                 = tCon cEq
pOrd                                = tCon cOrd
pIdentity                           = tCon cIdentity
pContainer a                        = tCon (cContainer a)
pContextManager                     = tCon cContextManager
