name: "\U0001F41E Bug Report"
description: "Create a bug report for Acton."
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        A bug is when something works differently than it is expected to.
        ## Remember to search before filing a new report
        Please search for this bug in the issue tracker, and use a bug report title that would have made your bug report turn up in the search results for your search query.
  - type: input
    id: version
    attributes:
      label: Acton Version
      description: "The output of `acton version`"
      placeholder: "0.16.3"
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Steps to Reproduce and Observed Behavior
      description: What exactly can someone else do, in order to observe the problem that you observed? Include the output and all error messages.
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen instead?
    validations:
      required: true
