# Resolver to choose a 'specific' stackage snapshot or a compiler version.
# A snapshot resolver dictates the compiler version and the set of packages
# to be used for project dependencies.

# NOTE: do not forget to update homebrew/Formula/acton.rb with the version of
# GHC that corresponds to the stack LTS release, like lts-18.28 -> ghc@8.10
snapshot: lts-22.34

# User packages to be built.
# Various formats can be used as shown in the example below.
#
# packages:
# - some-directory
# - https://example.com/foo/bar/baz-0.0.2.tar.gz
# - location:
#    git: https://github.com/commercialhaskell/stack.git
#    commit: e7b331f14bcffb8367cd58fbfc8b40ec7642100a
# - location: https://github.com/commercialhaskell/stack/commit/e7b331f14bcffb8367cd58fbfc8b40ec7642100a
#   extra-dep: true
#  subdirs:
#  - auto-update
#  - wai
#
# A package marked 'extra-dep: true' will only be built if demanded by a
# non-dependency (i.e. a user package), and its test suites and benchmarks
# will not be run. This is useful for tweaking upstream packages.
packages:
- lib
- actonc
- lsp-server
# Dependency packages to be pulled from upstream that are not in the resolver
# (e.g., acme-missiles-0.3)
# extra-deps: []
extra-deps:
  - Cabal-3.10.3.0
  - Cabal-syntax-3.10.3.0
  - diagnose-2.5.1@sha256:853fd268d7fe0191b79d73187104bf7b4bc5ce3bc3483cb088dc10b09f18abc8
  - dir-traverse-0.2.3.0
  - directory-1.3.8.5
  - filepath-1.4.300.1
  - lsp-2.7.0.0
  - lsp-types-2.3.0.0
  - parsec-3.1.17.0@sha256:8407cbd428d7f640a0fff8891bd2f7aca13cebe70a5e654856f8abec9a648b56
  - process-1.6.19.0
  - text-2.0@sha256:f2207a6a51a8320c44dbd8b462723a8e39e2bfceda67e15f52fc12922259cbb0
  - unix-2.8.2.1

# Override default flag values for local packages and extra-deps
# flags: {}

# Extra package databases containing global packages
# extra-package-dbs: []

# Control whether we use the GHC we find on the path
# NOTE: this is disabled so we can use a stack GHC in local dev environments but
# we rewrite this in our Homebrew recipe to use the system GHC. Do NOT remove
# this line, regexp replace matches on it!
# system-ghc: true

ghc-options:
  "$everything": -fPIC
