#!/usr/bin/env python3
"""Generate the class-heavy concurrent type-checking fixture."""

import argparse
from pathlib import Path


ROOTS = "ABCDEFGH"
SHAPES = [
    ("", None),
    ("1", ""),
    ("2", ""),
    ("2A", "2"),
    ("2A1", "2A"),
    ("2A2", "2A"),
    ("2B", "2"),
    ("3", ""),
    ("3A", "3"),
    ("3A1", "3A"),
]


def pad(n, width):
    return str(n).zfill(width)


def class_name(tree, suffix):
    band = tree // len(ROOTS)
    root = ROOTS[tree % len(ROOTS)]
    return "Node{}{}{}".format(pad(band, 3), root, suffix)


def method_name(name):
    return name.lower()


def emit_class(out, tree, suffix, parent_suffix, index):
    name = class_name(tree, suffix)
    parent = "object" if parent_suffix is None else class_name(tree, parent_suffix)
    method = method_name(name)
    branch = "branch_{}".format(pad(index, 5))
    extra = "extra_{}".format(pad(index, 5))
    root_class = parent_suffix is None
    n = index

    out.append("class {}({}):".format(name, parent))
    if root_class:
        out.append("    seed: int")
        out.append("    total: int")
        out.append("    weight: int")
    out.append("    {}: int".format(branch))
    out.append("    {}: int".format(extra))
    out.append("    __init__ : (int) -> None")
    out.append("    fold_{} : (int, int, int) -> int".format(method))
    out.append("    score_{} : (int) -> int".format(method))
    out.append("")
    out.append("    def __init__(self, seed):")
    if root_class:
        out.append("        self.seed = seed + {}".format(n))
        out.append("        self.total = self.seed + seed + {}".format(n + 1))
        out.append("        self.weight = self.total + self.seed + {}".format(n + 2))
        out.append("        self.{} = seed + self.seed + self.total + {}".format(branch, n + 3))
        out.append("        self.{} = self.{} + self.weight + {}".format(extra, branch, n + 4))
    else:
        out.append("        self.{} = seed + {}".format(branch, n + 4))
        out.append("        self.{} = self.{} + seed + {}".format(extra, branch, n + 5))
        out.append("        {}.__init__(self, seed + {})".format(parent, n + 1))
    out.append("")
    out.append("    def fold_{}(self, x, y, z):".format(method))
    out.append("        v0: int = x + y + z + self.seed + {}".format(n))
    for i in range(1, 15):
        attr = branch if i % 2 else extra
        out.append("        v{}: int = v{} + self.{} + self.total + {}".format(i, i - 1, attr, n + i))
    out.append("        return v14")
    out.append("")
    out.append("    def score_{}(self, bonus):".format(method))
    out.append("        r0: int = self.fold_{}(self.seed, self.total, self.weight) + bonus".format(method))
    for i in range(1, 11):
        attr = extra if i % 2 else branch
        out.append("        r{}: int = r{} + self.{} + self.weight + {}".format(i, i - 1, attr, n + i))
    out.append("        return r10")
    out.append("")
    out.append("_sep_{}: int = {}".format(pad(index, 5), index))
    out.append("")


def render(trees, command):
    classes = trees * len(SHAPES)
    top_stmts = classes * 2
    bands = (trees + len(ROOTS) - 1) // len(ROOTS)
    out = [
        "# Generated by generate_heavy.py. Do not edit by hand.",
        "#",
        "# Example:",
        "#   {}".format(command),
        "#",
        "# Heavy total top-level class hierarchy used to benchmark concurrent type checking.",
        "#",
        "# Shape per tree:",
        "#   NodeNNNA",
        "#     NodeNNNA1",
        "#     NodeNNNA2",
        "#       NodeNNNA2A",
        "#         NodeNNNA2A1",
        "#         NodeNNNA2A2",
        "#       NodeNNNA2B",
        "#     NodeNNNA3",
        "#       NodeNNNA3A",
        "#         NodeNNNA3A1",
        "#",
        "# This file contains {} ten-node trees across {} bands, producing".format(trees, bands),
        "# {} total classes and {} top-level statements. Every class is total:".format(classes, top_stmts),
        "# properties are declared, and method signatures are written as class",
        "# signatures before the corresponding method definitions.",
        "#",
        "# The tiny typed _sep_N assignments intentionally break adjacent class",
        "# declarations into separate top-level statements, so the concurrent type",
        "# checker can schedule each total class independently.",
        "",
    ]

    index = 1
    for tree in range(trees):
        for suffix, parent_suffix in SHAPES:
            emit_class(out, tree, suffix, parent_suffix, index)
            index += 1
    return "\n".join(out).rstrip() + "\n"


def parse_args():
    parser = argparse.ArgumentParser(description=__doc__)
    size = parser.add_mutually_exclusive_group()
    size.add_argument("--bands", type=int,
                      help="number of A-H bands to generate; each band is 80 classes")
    size.add_argument("--trees", type=int, default=40,
                      help="number of ten-class hierarchy trees to generate; default is 40")
    parser.add_argument("-o", "--output", type=Path,
                        default=Path("src/concurrent_typecheck_class_heavy.act"),
                        help="output .act file")
    return parser.parse_args()


def main():
    args = parse_args()
    trees = args.bands * len(ROOTS) if args.bands is not None else args.trees
    if trees < 1:
        raise SystemExit("size must be at least one tree")

    command = "./generate_heavy.py --trees {}".format(trees)
    if args.output != Path("src/concurrent_typecheck_class_heavy.act"):
        command += " --output {}".format(args.output)

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(render(trees, command))

    classes = trees * len(SHAPES)
    print("wrote {} trees, {} classes, {} top-level statements to {}".format(
        trees, classes, classes * 2, args.output
    ))


if __name__ == "__main__":
    main()
