#include "builtin.h"

#include "common.c"
#include "allprotocols.c"
#include "int.c"
#include "float.c"
#include "bool.c"
#include "Iterator.c"
#include "slice.c"
#include "hash.c"
#include "list.c"
#include "list_impl.c"
#include "dict.c"
#include "dict_impl.c"
#include "str.c"
#include "set.c"
#include "set_impl.c"
