/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: db_messages.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "db_messages.pb-c.h"
void   node_state_message__init
                     (NodeStateMessage         *message)
{
  static const NodeStateMessage init_value = NODE_STATE_MESSAGE__INIT;
  *message = init_value;
}
size_t node_state_message__get_packed_size
                     (const NodeStateMessage *message)
{
  assert(message->base.descriptor == &node_state_message__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t node_state_message__pack
                     (const NodeStateMessage *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &node_state_message__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t node_state_message__pack_to_buffer
                     (const NodeStateMessage *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &node_state_message__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
NodeStateMessage *
       node_state_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (NodeStateMessage *)
     protobuf_c_message_unpack (&node_state_message__descriptor,
                                allocator, len, data);
}
void   node_state_message__free_unpacked
                     (NodeStateMessage *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &node_state_message__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   gossip_message__init
                     (GossipMessage         *message)
{
  static const GossipMessage init_value = GOSSIP_MESSAGE__INIT;
  *message = init_value;
}
size_t gossip_message__get_packed_size
                     (const GossipMessage *message)
{
  assert(message->base.descriptor == &gossip_message__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t gossip_message__pack
                     (const GossipMessage *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &gossip_message__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t gossip_message__pack_to_buffer
                     (const GossipMessage *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &gossip_message__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
GossipMessage *
       gossip_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (GossipMessage *)
     protobuf_c_message_unpack (&gossip_message__descriptor,
                                allocator, len, data);
}
void   gossip_message__free_unpacked
                     (GossipMessage *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &gossip_message__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   membership_view_message__init
                     (MembershipViewMessage         *message)
{
  static const MembershipViewMessage init_value = MEMBERSHIP_VIEW_MESSAGE__INIT;
  *message = init_value;
}
size_t membership_view_message__get_packed_size
                     (const MembershipViewMessage *message)
{
  assert(message->base.descriptor == &membership_view_message__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t membership_view_message__pack
                     (const MembershipViewMessage *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &membership_view_message__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t membership_view_message__pack_to_buffer
                     (const MembershipViewMessage *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &membership_view_message__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
MembershipViewMessage *
       membership_view_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (MembershipViewMessage *)
     protobuf_c_message_unpack (&membership_view_message__descriptor,
                                allocator, len, data);
}
void   membership_view_message__free_unpacked
                     (MembershipViewMessage *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &membership_view_message__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   membership_agreement_message__init
                     (MembershipAgreementMessage         *message)
{
  static const MembershipAgreementMessage init_value = MEMBERSHIP_AGREEMENT_MESSAGE__INIT;
  *message = init_value;
}
size_t membership_agreement_message__get_packed_size
                     (const MembershipAgreementMessage *message)
{
  assert(message->base.descriptor == &membership_agreement_message__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t membership_agreement_message__pack
                     (const MembershipAgreementMessage *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &membership_agreement_message__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t membership_agreement_message__pack_to_buffer
                     (const MembershipAgreementMessage *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &membership_agreement_message__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
MembershipAgreementMessage *
       membership_agreement_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (MembershipAgreementMessage *)
     protobuf_c_message_unpack (&membership_agreement_message__descriptor,
                                allocator, len, data);
}
void   membership_agreement_message__free_unpacked
                     (MembershipAgreementMessage *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &membership_agreement_message__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   vector_clock_message__init
                     (VectorClockMessage         *message)
{
  static const VectorClockMessage init_value = VECTOR_CLOCK_MESSAGE__INIT;
  *message = init_value;
}
size_t vector_clock_message__get_packed_size
                     (const VectorClockMessage *message)
{
  assert(message->base.descriptor == &vector_clock_message__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t vector_clock_message__pack
                     (const VectorClockMessage *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &vector_clock_message__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t vector_clock_message__pack_to_buffer
                     (const VectorClockMessage *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &vector_clock_message__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
VectorClockMessage *
       vector_clock_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (VectorClockMessage *)
     protobuf_c_message_unpack (&vector_clock_message__descriptor,
                                allocator, len, data);
}
void   vector_clock_message__free_unpacked
                     (VectorClockMessage *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &vector_clock_message__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor node_state_message__field_descriptors[4] =
{
  {
    "status",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(NodeStateMessage, status),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "node_id",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(NodeStateMessage, node_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rack_id",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(NodeStateMessage, rack_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dc_id",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(NodeStateMessage, dc_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned node_state_message__field_indices_by_name[] = {
  3,   /* field[3] = dc_id */
  1,   /* field[1] = node_id */
  2,   /* field[2] = rack_id */
  0,   /* field[0] = status */
};
static const ProtobufCIntRange node_state_message__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor node_state_message__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "NodeStateMessage",
  "NodeStateMessage",
  "NodeStateMessage",
  "",
  sizeof(NodeStateMessage),
  4,
  node_state_message__field_descriptors,
  node_state_message__field_indices_by_name,
  1,  node_state_message__number_ranges,
  (ProtobufCMessageInit) node_state_message__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor gossip_message__field_descriptors[2] =
{
  {
    "node_state",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(GossipMessage, node_state),
    &node_state_message__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "vc",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(GossipMessage, vc),
    &vector_clock_message__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned gossip_message__field_indices_by_name[] = {
  0,   /* field[0] = node_state */
  1,   /* field[1] = vc */
};
static const ProtobufCIntRange gossip_message__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor gossip_message__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "GossipMessage",
  "GossipMessage",
  "GossipMessage",
  "",
  sizeof(GossipMessage),
  2,
  gossip_message__field_descriptors,
  gossip_message__field_indices_by_name,
  1,  gossip_message__number_ranges,
  (ProtobufCMessageInit) gossip_message__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor membership_view_message__field_descriptors[2] =
{
  {
    "membership",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(MembershipViewMessage, n_membership),
    offsetof(MembershipViewMessage, membership),
    &node_state_message__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "view_id",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(MembershipViewMessage, view_id),
    &vector_clock_message__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned membership_view_message__field_indices_by_name[] = {
  0,   /* field[0] = membership */
  1,   /* field[1] = view_id */
};
static const ProtobufCIntRange membership_view_message__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor membership_view_message__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "MembershipViewMessage",
  "MembershipViewMessage",
  "MembershipViewMessage",
  "",
  sizeof(MembershipViewMessage),
  2,
  membership_view_message__field_descriptors,
  membership_view_message__field_indices_by_name,
  1,  membership_view_message__number_ranges,
  (ProtobufCMessageInit) membership_view_message__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor membership_agreement_message__field_descriptors[4] =
{
  {
    "msg_type",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(MembershipAgreementMessage, msg_type),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ack_status",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(MembershipAgreementMessage, ack_status),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "view",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(MembershipAgreementMessage, view),
    &membership_view_message__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "vc",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(MembershipAgreementMessage, vc),
    &vector_clock_message__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned membership_agreement_message__field_indices_by_name[] = {
  1,   /* field[1] = ack_status */
  0,   /* field[0] = msg_type */
  3,   /* field[3] = vc */
  2,   /* field[2] = view */
};
static const ProtobufCIntRange membership_agreement_message__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor membership_agreement_message__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "MembershipAgreementMessage",
  "MembershipAgreementMessage",
  "MembershipAgreementMessage",
  "",
  sizeof(MembershipAgreementMessage),
  4,
  membership_agreement_message__field_descriptors,
  membership_agreement_message__field_indices_by_name,
  1,  membership_agreement_message__number_ranges,
  (ProtobufCMessageInit) membership_agreement_message__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor vector_clock_message__field_descriptors[2] =
{
  {
    "ids",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_INT32,
    offsetof(VectorClockMessage, n_ids),
    offsetof(VectorClockMessage, ids),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "counters",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_INT64,
    offsetof(VectorClockMessage, n_counters),
    offsetof(VectorClockMessage, counters),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned vector_clock_message__field_indices_by_name[] = {
  1,   /* field[1] = counters */
  0,   /* field[0] = ids */
};
static const ProtobufCIntRange vector_clock_message__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor vector_clock_message__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "VectorClockMessage",
  "VectorClockMessage",
  "VectorClockMessage",
  "",
  sizeof(VectorClockMessage),
  2,
  vector_clock_message__field_descriptors,
  vector_clock_message__field_indices_by_name,
  1,  vector_clock_message__number_ranges,
  (ProtobufCMessageInit) vector_clock_message__init,
  NULL,NULL,NULL    /* reserved[123] */
};
