
on:
  workflow_call:
    inputs:
      repo_url:
        required: true
        type: string
      arch:
        required: false
        type: string
        default: "amd64"

jobs:
  test-app:
    runs-on: ubuntu-24.04${{ inputs.arch == 'arm64' && '-arm' || '' }}
    steps:
      - name: "Install gdb"
        run: |
          sudo apt update
          sudo apt install -y gdb
      - name: "Download .deb files"
        uses: actions/download-artifact@v6
        with:
          name: acton-debs-${{ inputs.arch }}
      - name: "Install acton from .deb"
        run: |
          sudo apt install -y ./deb/acton_*.deb
          acton version
      - name: "Clone app repo"
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.repo_url }}
          path: app
      - name: "Compile acton program"
        run: |
          cd app
          acton build
          acton test
          acton test perf
