
on:
  workflow_call:
    inputs:
      repo_url:
        required: true
        type: string
      arch:
        required: false
        type: string
        default: "amd64"
      branch:
        required: false
        type: string

jobs:
  test-app:
    runs-on: ubuntu-24.04${{ inputs.arch == 'arm64' && '-arm' || '' }}
    steps:
      - name: "Install gdb"
        run: |
          sudo apt update
          sudo apt install -y gdb
      - name: "Download .deb files"
        uses: actions/download-artifact@v4
        with:
          name: acton-debs-${{ inputs.arch }}
      - name: "Install acton from .deb"
        run: |
          sudo apt install -y ./deb/acton_*.deb
          acton --version
      - name: "Clone app repo with default branch"
        if: inputs.branch == ''
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.repo_url }}
          path: app
          
      - name: "Clone app repo with specific branch"
        if: inputs.branch != ''
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.repo_url }}
          path: app
          ref: ${{ inputs.branch }}
      - name: "Compile acton program"
        run: |
          cd app
          acton build
          for ((i = 0; i < 1000; i++)); do out/bin/test_ttt_callbacks; echo "\n\n\n"; done
          acton test
          acton test perf
