name: Trigger rebuild of Acton Web page

# When there are changes to files under docs/acton-by-example on main branch,
# trigger the workflow to rebuild the Acton web page
on:
  push:
    branches:
      - main
    paths:
      - 'docs/acton-by-example/**'

jobs:
  trigger_web_rebuild:
    runs-on: ubuntu-latest

    steps:
      - name: "Trigger build of www.acton-lang.org"
        uses: benc-uk/workflow-dispatch@v1
        with:
          repo: actonlang/www.acton-lang.org
          token: ${{ secrets.ACTBOT_PAT }}
          workflow: main.yml
          ref: main
      - name: "Trigger build of acton.guide"
        uses: benc-uk/workflow-dispatch@v1
        with:
          repo: actonlang/acton.guide
          token: ${{ secrets.ACTBOT_PAT }}
          workflow: main.yml
          ref: main
